"use client";
import {useEffect,useState} from 'react';
import {BackupControls} from '@/components/backup-controls';
import {db} from '@/lib/db';
import {useLibrary,LibraryState} from '@/components/library-provider';
export default function Settings(){
 const {loading,error,refresh}=useLibrary();const [code,setCode]=useState('');const [stored,setStored]=useState(false);const [verified,setVerified]=useState(false);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(loading||error)return;let alive=true;function readSettings(){return db.meta.get('verified-only').then(m=>{if(!alive)return;setVerified(m?.value==='true');try{setStored(!!localStorage.getItem('murajaah-access-code'));}catch{setMessage('Browser tidak mengizinkan penyimpanan kode akses.');}}).catch(()=>{if(alive)setMessage('Pengaturan belum dapat dibaca.');});}void readSettings();window.addEventListener('murajaah-settings-changed',readSettings);return()=>{alive=false;window.removeEventListener('murajaah-settings-changed',readSettings);};},[loading,error]);
 async function save(){setBusy(true);try{if(code){if(code.length<24)throw new Error('Kode akses harus minimal 24 karakter, sesuai konfigurasi server.');localStorage.setItem('murajaah-access-code',code);setStored(true);setCode('');}await db.meta.put({key:'verified-only',value:String(verified)});await refresh();setMessage('Pengaturan tersimpan. Kode akan diperiksa saat Anda membuat draf.');}catch(e){setMessage(e instanceof Error?e.message:'Pengaturan belum tersimpan.');}finally{setBusy(false);}}
 if(loading||error)return <LibraryState/>;
 return <><header className="page-head"><p className="eyebrow">RUANG PRIBADI</p><h1>Pengaturan</h1><p>Data belajar tersimpan di browser pada perangkat ini.</p></header><section className="quiz-panel"><h2>Akses pembuatan materi</h2><p>Kode akses melindungi penggunaan AI lokal. Masukkan kode yang sama dengan konfigurasi server, sekali pada perangkat ini.</p><label className="field">Kode akses<input type="password" autoComplete="off" maxLength={512} value={code} onChange={e=>setCode(e.target.value)} placeholder={stored?'Kode tersimpan · isi untuk mengganti':'Minimal 24 karakter'}/></label>{stored&&<button className="text-link plain-button" onClick={()=>{try{localStorage.removeItem('murajaah-access-code');setStored(false);setMessage('Kode akses dihapus dari perangkat ini.');}catch{setMessage('Kode belum dapat dihapus.');}}}>Hapus kode tersimpan</button>}<p className="muted">Kode akses disimpan di browser. AI diproses dengan Ollama lokal tanpa biaya API; layanan cloud dan berbayar diblokir. Gunakan perangkat pribadi; kode ini bukan sistem login.</p><label className="choice"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Hanya materi terverifikasi</label><p className="muted">Berlaku pada perpustakaan dan soal kuis. Materi awal berstatus Draf, sehingga disembunyikan jika filter ini aktif.</p><button className="button" disabled={busy} onClick={save}>{busy?'Menyimpan…':'Simpan pengaturan'}</button><p role="status" aria-label="Status pengaturan">{message}</p></section><BackupControls/><p className="footnote">Menghapus data browser akan menghapus materi dan kemajuan. Unduh cadangan secara berkala.</p></>;
}
