import 'fake-indexeddb/auto';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {acceptDriveToken,clearDriveSession,hasDriveSession,driveScope,listDriveBackups,uploadDriveBackup,downloadDriveBackup,maxBackupBytes} from '../lib/drive-backup';
import type {Backup} from '../lib/backup';
const backup:Backup={format:'murajaah',version:1,exportedAt:'2026-10-07T00:00:00.000Z',subjects:[],topics:[],lessons:[],questions:[],attempts:[],readings:[],notes:[],meta:[]};
const file={id:'file_1',name:'murajaah.json',modifiedTime:'2026-10-07T00:00:00.000Z',size:'100'};
beforeEach(()=>{clearDriveSession();acceptDriveToken({access_token:'user-owned-test-token',expires_in:3600,scope:driveScope});});
afterEach(()=>{clearDriveSession();vi.unstubAllGlobals();vi.useRealTimers();});
describe('private Drive snapshots',()=>{
 it('requires the narrow application scope and expires tokens without persistence',()=>{clearDriveSession();expect(()=>acceptDriveToken({access_token:'wrong',expires_in:3600,scope:'https://www.googleapis.com/auth/drive'})).toThrow();expect(hasDriveSession()).toBe(false);vi.useFakeTimers();acceptDriveToken({access_token:'local-memory-only',expires_in:60,scope:driveScope});vi.advanceTimersByTime(31000);expect(hasDriveSession()).toBe(false);});
 it('lists only app backups under the selected user token',async()=>{const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({files:[file]})));vi.stubGlobal('fetch',fetch);expect((await listDriveBackups()).files).toEqual([file]);const [url,options]=fetch.mock.calls[0];expect(url).toContain('spaces=appDataFolder');expect(url).toContain('appProperties');expect(options.headers.Authorization).toBe('Bearer user-owned-test-token');expect(options.redirect).toBe('error');});
 it('creates a new MIME multipart snapshot rather than overwriting previous data',async()=>{const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify(file)));vi.stubGlobal('fetch',fetch);await uploadDriveBackup(backup);const [url,options]=fetch.mock.calls[0];expect(url).toContain('uploadType=multipart');expect(options.method).toBe('POST');expect(options.headers['Content-Type']).toMatch(/^multipart\/related; boundary=/);const body=await options.body.text();expect(body).toContain('"parents":["appDataFolder"]');expect(body).toContain('"format":"murajaah"');expect(body).not.toContain('user-owned-test-token');});
 it('validates downloaded snapshots and rejects malformed files and unsafe file IDs',async()=>{const fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(backup))).mockResolvedValueOnce(new Response('{bad'));vi.stubGlobal('fetch',fetch);expect(await downloadDriveBackup(file)).toEqual(backup);await expect(downloadDriveBackup(file)).rejects.toThrow('tidak valid');await expect(downloadDriveBackup({...file,id:'../../escape'})).rejects.toThrow();expect(fetch).toHaveBeenCalledTimes(2);});
 it('rejects oversize metadata before downloading and bounds streamed contents',async()=>{const fetch=vi.fn().mockResolvedValue(new Response(new Uint8Array(maxBackupBytes+1)));vi.stubGlobal('fetch',fetch);await expect(downloadDriveBackup({...file,size:String(maxBackupBytes+1)})).rejects.toThrow('20 MB');expect(fetch).not.toHaveBeenCalled();await expect(downloadDriveBackup(file)).rejects.toThrow('20 MB');});
 it('does not silently retry quota failures and clears unauthorized sessions',async()=>{const fetch=vi.fn().mockResolvedValueOnce(new Response('',{status:403})).mockResolvedValueOnce(new Response('',{status:401}));vi.stubGlobal('fetch',fetch);await expect(listDriveBackups()).rejects.toThrow('kuota');expect(fetch).toHaveBeenCalledTimes(1);await expect(listDriveBackups()).rejects.toThrow('Sesi');expect(hasDriveSession()).toBe(false);await expect(listDriveBackups()).rejects.toThrow('Sesi');expect(fetch).toHaveBeenCalledTimes(2);});
});
