import {describe,it,expect} from 'vitest';
import {generationInputSchema,groundDraft,validateDraft} from '../lib/generation';
import {GenerationLimiter,validAccessCode} from '../lib/ai/security';
import {OpenAIProvider,createProvider} from '../lib/ai/provider';
import {fixture,input} from './fixtures/draft';
describe('content integrity',()=>{
 it('overrides model book attribution with supplied reference only',()=>{const d=groundDraft(fixture(),input,[]);expect(d.lessons[0].sourceRef).toEqual({title:input.reference,locator:input.locator,url:''});});
 it('requires exact evidence for pasted sources',()=>{const d=fixture();d.questions[0].evidence='Invented source';expect(()=>groundDraft(d,input,[])).toThrow();});
 it('rejects unsourced Arabic and does not transcribe photos',()=>{const d=fixture();d.lessons[0].examples=[{arabic:'نْ',transliteration:'nun',meaning:'huruf',note:'latihan'}];expect(()=>groundDraft(d,input,[])).toThrow();expect(()=>groundDraft(d,{...input,suppliedText:'',photos:['data:image/jpeg;base64,YQ==']},[])).toThrow();expect(groundDraft(d,{...input,suppliedText:input.suppliedText+' نْ'},[]).lessons[0].examples).toHaveLength(1);});
 it('requires observed source URLs and labels ungrounded output as general',()=>{const d=fixture();d.lessons[0].sourceRef.url=d.questions[0].sourceRef.url='https://example.org/rule';const ungrounded={...input,suppliedText:''};expect(()=>groundDraft(d,ungrounded,[])).toThrow();expect(groundDraft(d,ungrounded,['https://example.org/rule']).questions[0].sourceRef.title).toContain('Rujukan umum');});
 it('rejects script URLs, bad answer indexes, orphan lessons, repeated options and missing fields',()=>{let d=fixture();d.questions[0].sourceRef.url='javascript:alert(1)';expect(()=>validateDraft(d)).toThrow();d=fixture();d.questions[0].correctIndex=4;expect(()=>validateDraft(d)).toThrow();d=fixture();d.questions[0].lessonIndex=2;expect(()=>validateDraft(d)).toThrow();d=fixture();d.questions[0].options=['sama','sama'];expect(()=>validateDraft(d)).toThrow();expect(()=>validateDraft({})).toThrow();});
 it('caps photo count and rejects non-JPEG data',()=>{expect(generationInputSchema.safeParse({...input,photos:Array(5).fill('data:image/jpeg;base64,YQ==')}).success).toBe(false);expect(generationInputSchema.safeParse({...input,photos:['https://example.org/photo.jpg']}).success).toBe(false);});
});
describe('security and adapter',()=>{
 it('rejects missing/incorrect/short codes',()=>{expect(validAccessCode(null,'a'.repeat(24))).toBe(false);expect(validAccessCode('a'.repeat(24),'a'.repeat(24))).toBe(true);expect(validAccessCode('b'.repeat(24),'a'.repeat(24))).toBe(false);expect(validAccessCode('short','short')).toBe(false);});
 it('limits concurrency, minute and hour buckets and releases after wait',()=>{const l=new GenerationLimiter();expect(l.acquire(0).allowed).toBe(true);expect(l.acquire(1).allowed).toBe(false);l.release();for(let n=1;n<3;n++){expect(l.acquire(n).allowed).toBe(true);l.release();}expect(l.acquire(3).allowed).toBe(false);for(let n=3;n<12;n++){expect(l.acquire(n*60001).allowed).toBe(true);l.release();}expect(l.acquire(800000).allowed).toBe(false);expect(l.acquire(3600001).allowed).toBe(true);});
 it('fails closed for missing config or unsupported providers',()=>{expect(()=>createProvider({})).toThrow();expect(()=>createProvider({AI_PROVIDER:'other',AI_MODEL:'env-model',AI_API_KEY:'test-only'})).toThrow();});
 it('uses environment-selected model and disables search for supplied material',async()=>{let sent:Record<string,unknown>={};const request:typeof fetch=async(_url,init)=>{sent=JSON.parse(String(init?.body));return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(fixture())}]}]});};const result=await new OpenAIProvider('test-only','environment-model',request).generate(input);expect(sent.model).toBe('environment-model');expect(sent.store).toBe(false);expect(sent.tools).toBeUndefined();expect(result.lessons[0].sourceRef.title).toBe(input.reference);});
 it('enforces search and validates source provenance for general materials',async()=>{let sent:Record<string,unknown>={};const d=fixture();d.lessons[0].sourceRef.url=d.questions[0].sourceRef.url='https://example.org/rule';const request:typeof fetch=async(_url,init)=>{sent=JSON.parse(String(init?.body));return Response.json({status:'completed',output:[{type:'web_search_call',action:{sources:[{url:'https://example.org/rule'}]}},{type:'message',content:[{type:'output_text',text:JSON.stringify(d)}]}]});};await new OpenAIProvider('test-only','environment-model',request).generate({...input,suppliedText:''});expect(sent.tool_choice).toBe('required');expect(sent.tools).toEqual([{type:'web_search'}]);});
 it('rejects incomplete and malformed AI output',async()=>{const request:typeof fetch=async()=>Response.json({status:'incomplete',output:[]});await expect(new OpenAIProvider('test-only','env-model',request).generate(input)).rejects.toThrow();});
});
