import 'fake-indexeddb/auto';
import {installLegacyFixture} from './fixtures/legacy-library';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {db,initialize} from '../lib/db';
import {readLessonSnapshot,updateLesson,deleteLesson} from '../lib/lessons';
beforeEach(async()=>{await db.open();await initialize();await installLegacyFixture();});afterEach(async()=>{await db.delete();});
async function withHistory(){await db.readings.put({lessonId:'nun',completedAt:1});await db.attempts.bulkPut([{id:'nun-attempt',questionId:'q-0',correct:true,answeredAt:1,box:2},{id:'mim-attempt',questionId:'q-5',correct:true,answeredAt:1,box:2}]);return readLessonSnapshot('nun');}
describe('material management',()=>{
 it('saves edits while preserving IDs, origin and unrelated data',async()=>{const s=await withHistory();const questions=s.questions.map(q=>({...q,status:'draft' as const}));await updateLesson(s,{...s.lesson,title:'Judul disunting',explanation:'Penjelasan diperbaiki'},questions);expect(await db.lessons.get('nun')).toMatchObject({title:'Judul disunting',origin:'seed'});expect(await db.readings.get('nun')).toBeUndefined();expect(await db.attempts.count()).toBe(2);expect(await db.lessons.get('mim')).toBeDefined();});
 it('only invalidates history for removed or substantively changed questions',async()=>{const s=await withHistory();const changed=s.questions.map(q=>q.id==='q-0'?{...q,correctIndex:1}:q).filter(q=>q.id!=='q-1');await updateLesson(s,s.lesson,changed);expect(await db.attempts.get('nun-attempt')).toBeUndefined();expect(await db.attempts.get('mim-attempt')).toBeDefined();expect(await db.questions.get('q-1')).toBeUndefined();expect(await db.readings.get('nun')).toBeDefined();});
 it('deletes a lesson with its questions, history and reading only',async()=>{const s=await withHistory();await deleteLesson(s);expect(await db.lessons.get('nun')).toBeUndefined();expect(await db.questions.where('lessonId').equals('nun').count()).toBe(0);expect(await db.readings.get('nun')).toBeUndefined();expect(await db.attempts.get('nun-attempt')).toBeUndefined();expect(await db.attempts.get('mim-attempt')).toBeDefined();await initialize();expect(await db.lessons.get('nun')).toBeUndefined();});
 it('rejects stale editing and deletion snapshots without data loss',async()=>{const s=await withHistory();await db.lessons.update('nun',{title:'Versi tab lain'});await expect(updateLesson(s,s.lesson,s.questions)).rejects.toThrow('tab lain');await expect(deleteLesson(s)).rejects.toThrow('tab lain');expect((await db.lessons.get('nun'))?.title).toBe('Versi tab lain');expect(await db.attempts.count()).toBe(2);});
 it('rejects invalid answers, duplicate IDs and moving other lesson questions atomically',async()=>{const s=await withHistory();await expect(updateLesson(s,s.lesson,[{...s.questions[0],correctIndex:99}])).rejects.toThrow();await expect(updateLesson(s,s.lesson,[s.questions[0],s.questions[0]])).rejects.toThrow();const mim=(await db.questions.get('q-5'))!;await expect(updateLesson(s,{...s.lesson,title:'Tidak boleh tersimpan'},[{...mim,lessonId:'nun'}])).rejects.toThrow();expect(await db.questions.get('q-5')).toEqual(mim);expect((await db.lessons.get('nun'))?.title).toBe(s.lesson.title);expect(await db.attempts.count()).toBe(2);});
 it('rejects a missing topic without deleting data',async()=>{const s=await withHistory();await expect(updateLesson(s,{...s.lesson,topicId:'missing'},[])).rejects.toThrow('Topik');expect(await db.questions.where('lessonId').equals('nun').count()).toBe(5);expect(await db.attempts.count()).toBe(2);});
 it('rolls back question and history changes if the final write fails',async()=>{const s=await withHistory();const spy=vi.spyOn(db.lessons,'put').mockRejectedValue(new Error('Simulated disk failure'));try{await expect(updateLesson(s,{...s.lesson,title:'Tidak tersimpan'},[])).rejects.toThrow('disk failure');}finally{spy.mockRestore();}expect(await db.questions.where('lessonId').equals('nun').count()).toBe(5);expect(await db.attempts.count()).toBe(2);expect((await db.lessons.get('nun'))?.title).toBe(s.lesson.title);});
});
