import {it,expect} from 'vitest';
import {formatCalendar} from '../lib/calendar';
import {orderedLessons} from '../lib/lesson-order';
import {pdfLessons,pdfTopics} from '../lib/tuhfatul-athfal';
import {regenerateQuestions} from '../lib/quiz';
import {pdfQuestions} from '../lib/tuhfatul-athfal';
it('orders siblings consistently without crossing collections',()=>{const items=orderedLessons([...pdfLessons].reverse(),pdfTopics,'tuhfatul-athfal');expect(items[0].id).toBe('tuhfah-pengantar');expect(items[1].id).toBe('tuhfah-nun');expect(items.at(-1)?.id).toBe('tuhfah-ghunnah');expect(orderedLessons(pdfLessons,pdfTopics,'missing')).toEqual([]);});
it('regenerates a disjoint quiz when enough questions remain and respects finite pools',()=>{const previous=pdfQuestions.slice(0,5);const next=regenerateQuestions(pdfQuestions,5,[],previous,()=>0.5);expect(next).toHaveLength(5);expect(next.every(q=>!previous.some(p=>p.id===q.id))).toBe(true);const only=regenerateQuestions([previous[0]],5,[],[previous[0]],()=>0.5);expect(only[0].options).not.toEqual(previous[0].options);expect(only[0].options[only[0].correctIndex]).toBe(previous[0].options[0]);const small=regenerateQuestions(previous,5,[],previous,()=>0.5);expect(new Set(small.map(q=>q.id)).size).toBe(5);expect(small.map(q=>q.id)).not.toEqual(previous.map(q=>q.id));small.forEach(q=>expect(q.options[q.correctIndex]).toBe(previous.find(p=>p.id===q.id)!.options[0]));});
it('formats dates at local midnight and Hijri month/year boundaries',()=>{const before=formatCalendar(new Date('2026-10-06T16:59:59Z'),'Asia/Jakarta');const after=formatCalendar(new Date('2026-10-06T17:00:00Z'),'Asia/Jakarta');expect(before.clock).toMatch(/23[.:]59[.:]59/);expect(after.clock).toMatch(/00[.:]00[.:]00/);expect(after.gregorian).toContain('7 Oktober 2026');expect(after.hijri).not.toBe(before.hijri);const newYear=formatCalendar(new Date('2025-06-27T05:00:00Z'),'UTC');expect(newYear.hijri).toContain('1447');expect(newYear.hijri).toMatch(/Muhar+am/i);});
