import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFile} from 'node:fs/promises';
const base=process.env.PUBLIC_BASE_PATH??'/';
const scope='https://www.googleapis.com/auth/drive.appdata';
test('Drive setup is optional and recovery guidance works offline',async({page,context})=>{let google=0;page.on('request',request=>{if(/googleapis|accounts\.google/.test(request.url()))google++;});await page.goto(`${base}#/pengaturan`);await expect(page.getByText('Koneksi Google Drive belum diaktifkan pengelola.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Hubungkan Google Drive'})).toHaveCount(0);expect(google).toBe(0);await expect(page.getByText('Salinan offline siap.',{exact:false})).toBeVisible();await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.goto(`${base}panduan-cadangan.html`);await expect(page.getByRole('heading',{name:'Cadangkan dan pulihkan data di HP',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Jika belum pernah membuat cadangan'})).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);});
test('private-account Drive backup, reviewed restore and token expiry preserve local data',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('murajaah-google-client-id','12345-murajaahmock.apps.googleusercontent.com'));
 let snapshot:Record<string,unknown>|undefined;let unauthorized=false;let uploadCount=0;
 await page.route('https://accounts.google.com/gsi/client',route=>route.fulfill({contentType:'text/javascript',body:`window.google={accounts:{oauth2:{initTokenClient:options=>({requestAccessToken:()=>{if(options.scope!==${JSON.stringify(scope)})throw Error('Excessive scope');options.callback({access_token:'chosen-user-token',expires_in:3600,scope:${JSON.stringify(scope)}});}}),revoke:(token,callback)=>callback()}}};`}));
 await page.route('https://www.googleapis.com/**',async route=>{const request=route.request();if(request.method()==='OPTIONS'){await route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST'}});return;}expect(request.headers().authorization).toBe('Bearer chosen-user-token');if(unauthorized){await route.fulfill({status:401,json:{error:'expired'}});return;}const url=new URL(request.url());const file={id:'own_account_snapshot',name:'murajaah-test.json',modifiedTime:'2026-10-07T00:00:00.000Z',size:'10000'};if(request.method()==='POST'){uploadCount++;expect(request.headers()['content-type']).toContain('multipart/related');const body=request.postData()!;expect(body).toContain('"parents":["appDataFolder"]');const boundary=request.headers()['content-type'].split('boundary=')[1];const media=body.split(`--${boundary}`)[2];snapshot=JSON.parse(media.slice(media.indexOf('\r\n\r\n')+4).trim());expect(JSON.stringify(snapshot)).not.toContain('chosen-user-token');await route.fulfill({json:file});}else if(url.searchParams.get('alt')==='media'){expect(snapshot).toBeTruthy();const restored=structuredClone(snapshot)!;const lessons=restored.lessons as {title:string}[];lessons[0].title='Materi dari cadangan akun sendiri';await route.fulfill({json:restored});}else{expect(url.searchParams.get('spaces')).toBe('appDataFolder');await route.fulfill({json:{files:snapshot?[file]:[]}});}});
 await page.goto(`${base}#/pengaturan`);await page.getByRole('button',{name:'Siapkan koneksi Google'}).click();await page.getByRole('button',{name:'Hubungkan Google Drive'}).click();await expect(page.getByRole('status',{name:'Status Google Drive'})).toContainText('terhubung');await page.getByRole('button',{name:'Simpan cadangan ke Drive'}).click();await expect(page.getByRole('status',{name:'Status Google Drive'})).toContainText('tersimpan');expect(uploadCount).toBe(1);await page.getByRole('button',{name:'Tinjau pemulihan dari Drive'}).click();await expect(page.getByRole('heading',{name:'Tinjau cadangan'})).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);await page.getByRole('button',{name:'Batalkan impor'}).click();await expect(page.getByRole('status',{name:'Status cadangan'})).toContainText('Data tidak berubah');await page.getByRole('button',{name:'Tinjau pemulihan dari Drive'}).click();await page.getByRole('button',{name:'Konfirmasi ganti data dan impor'}).click();await expect(page.getByRole('status',{name:'Status cadangan'})).toContainText('berhasil diimpor');
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Ekspor JSON',exact:true}).click();const download=await downloadEvent;const data=await readFile((await download.path())!,'utf8');expect(data).toContain('Materi dari cadangan akun sendiri');expect(data).not.toContain('chosen-user-token');expect(data).not.toContain('apps.googleusercontent.com');
 unauthorized=true;await page.getByRole('button',{name:'Lihat cadangan Drive'}).click();await expect(page.getByRole('status',{name:'Status Google Drive'})).toContainText('Sesi Google berakhir');await expect(page.getByRole('button',{name:'Simpan cadangan ke Drive'})).toHaveCount(0);expect(uploadCount).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
