import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const base=process.env.PUBLIC_BASE_PATH??'/';
test('notes edit, backup, source transfer and deletion preserve published material',async({page})=>{
 await page.goto(`${base}#/catatan`);await page.getByRole('button',{name:'Catatan baru',exact:true}).click();await page.getByLabel('Judul catatan').fill('Kajian tentang belajar');await page.getByLabel('Pemateri (opsional)').fill('Guru');await page.getByLabel('Isi catatan').fill('Belajar dilakukan dengan memahami, mencatat, dan mengulang.');await page.getByRole('button',{name:'Simpan catatan'}).click();await expect(page.getByRole('heading',{name:'Kajian tentang belajar'})).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
 await page.getByRole('button',{name:'Baca / edit'}).click();await page.getByLabel('Isi catatan').fill('Belajar dilakukan dengan memahami, mencatat, dan mengulang setiap hari.');await page.getByRole('button',{name:'Simpan catatan'}).click();await page.getByRole('link',{name:'Jadikan materi & kuis'}).click();await page.getByRole('button',{name:/Materi di subjek yang ada/}).click();await expect(page.getByLabel('Teks materi',{exact:false})).toHaveValue(/setiap hari/);await page.getByRole('button',{name:'Buat draf manual'}).click();await expect(page.getByRole('button',{name:'Kembali ke formulir'})).toBeVisible();await page.getByRole('button',{name:'Kembali ke formulir'}).click();await expect(page.getByLabel('Teks materi',{exact:false})).toHaveValue(/setiap hari/);await page.getByRole('button',{name:'Buat draf manual'}).click();await page.getByLabel('Saya sudah meninjau',{exact:false}).check();await page.getByRole('button',{name:'Terbitkan ke perpustakaan'}).click();await page.getByRole('link',{name:'Baca materi yang diterbitkan'}).click();await expect(page.locator('h1')).toHaveText('Kajian tentang belajar');const materialUrl=page.url();
 await page.getByRole('link',{name:'Catatan',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Hapus catatan Kajian tentang belajar'}).click();await expect(page.getByRole('heading',{name:'Kajian tentang belajar'})).toHaveCount(0);await page.goto(materialUrl);await expect(page.locator('h1')).toHaveText('Kajian tentang belajar');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('real PDF extraction retains page attribution and rejects invalid ranges',async({page})=>{
 await page.goto(`${base}#/tambah`);await page.getByRole('button',{name:/Subjek materi baru/}).click();await page.getByLabel('Nama subjek baru').fill('Buku kajian');await page.getByRole('button',{name:'Upload PDF',exact:true}).click();await page.getByLabel('File PDF').setInputFiles('public/references/terjemah-tuhfatul-athfal.pdf');await page.getByLabel('Dari halaman').fill('999');await page.getByLabel('Sampai halaman').fill('999');await page.getByRole('button',{name:'Baca teks PDF'}).click();await expect(page.getByRole('status')).toContainText('rentang');await page.getByLabel('Dari halaman').fill('5');await page.getByLabel('Sampai halaman').fill('6');await page.getByRole('button',{name:'Baca teks PDF'}).click();await expect(page.getByRole('status')).toContainText('Teks PDF siap');await expect(page.getByLabel('Teks materi',{exact:false})).toHaveValue(/\[Halaman 5\]/);await expect(page.getByLabel('Halaman / bab (opsional)')).toHaveValue(/PDF hlm\. 5–6/);await page.getByRole('button',{name:'Buat draf manual'}).click();await expect(page.getByRole('heading',{name:'Tinjau draf'})).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
});
test('quiz begins with introduction and browser AI gives explicit hardware requirements',async({page})=>{await page.goto(`${base}#/kuis`);await expect(page.getByRole('button',{name:'Mulai kuis',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Siapkan kuis'}).click();await expect(page.getByRole('button',{name:'Mulai kuis',exact:true})).toBeVisible();await page.getByRole('button',{name:'Buat soal baru dengan AI',exact:true}).click();await expect(page.getByText(/membutuhkan WebGPU/)).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);await page.getByRole('button',{name:'Kembali ke pengantar'}).click();await expect(page.getByRole('button',{name:'Siapkan kuis'})).toBeVisible();});
