import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const base=process.env.PUBLIC_BASE_PATH??'/';
test('public edition works offline and persists readings, quizzes and sources',async({page,context})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(base);await expect(page.getByRole('heading',{name:'Simpan di perangkat'})).toBeVisible();await expect(page.getByText('Salinan offline siap.',{exact:false})).toBeVisible();
 await page.evaluate(()=>new Promise<void>(resolve=>{if(navigator.serviceWorker.controller)resolve();else navigator.serviceWorker.addEventListener('controllerchange',()=>resolve(),{once:true});}));
 await page.getByRole('link',{name:'Baca materi',exact:true}).click();await expect(page.locator('h1')).toHaveText('Mengenal Tuhfatul Athfal');await page.getByRole('button',{name:'Tandai sudah dibaca',exact:true}).click();await expect(page.getByRole('button',{name:'Tandai belum dibaca',exact:true})).toBeVisible();
 await context.setOffline(true);await page.reload();await expect(page.getByRole('button',{name:'Tandai belum dibaca',exact:true})).toBeVisible();await page.getByRole('link',{name:/Materi selanjutnya/}).click();await expect(page.locator('h1')).toHaveText('Nun Sakinah dan Tanwin');
 await page.getByRole('link',{name:'Kuis',exact:true}).click();await page.getByRole('button',{name:'Siapkan kuis'}).click();await page.getByRole('button',{name:'Mulai kuis',exact:true}).click();for(let i=0;i<5;i++){await page.getByRole('radio').first().check();await page.getByRole('button',{name:'Periksa jawaban'}).click();await page.getByRole('button',{name:i===4?'Lihat hasil':'Soal berikutnya'}).click();}await expect(page.getByRole('heading',{name:'Sesi selesai'})).toBeVisible();await page.getByRole('button',{name:'Buat kuis baru'}).click();await expect(page.getByText('SOAL 1 DARI 5')).toBeVisible();
 const attempts=await page.evaluate(()=>new Promise<number>((resolve,reject)=>{const request=indexedDB.open('murajaah');request.onsuccess=()=>{const database=request.result;const count=database.transaction('attempts').objectStore('attempts').count();count.onsuccess=()=>{database.close();resolve(count.result);};count.onerror=()=>reject(count.error);};}));expect(attempts).toBe(5);
 const cached=await page.evaluate(async(base)=>{const cache=await caches.open((await caches.keys()).find(key=>key.startsWith('murajaah-'))!);return {pdf:!!await cache.match(base+'references/terjemah-tuhfatul-athfal.pdf'),font:!!await cache.match(base+'fonts/kfgqpc-uthmanic-hafs.otf')};},base);expect(cached).toEqual({pdf:true,font:true});expect(errors).toEqual([]);
});
test('manual creation, arbitrary lesson URL, editing, backup, and user isolation',async({page,browser})=>{
 let apiCalls=0;page.on('request',request=>{if(request.url().includes('/api/'))apiCalls++;});await page.goto(`${base}#/tambah`);await page.getByRole('button',{name:/Subjek materi baru/}).click();await page.getByLabel('Nama subjek baru').fill('Koleksi pribadi');await page.getByLabel('Topik',{exact:true}).fill('Latihan pribadi');await page.getByLabel('Referensi',{exact:true}).fill('Catatan guru');await page.getByLabel('Teks materi', {exact:false}).fill('Materi latihan yang hanya disimpan pada perangkat saya.');await page.getByRole('button',{name:'Buat draf manual'}).click();await expect(page.getByRole('heading',{name:'Tinjau draf'})).toBeVisible();
 await page.getByLabel('Saya sudah meninjau', {exact:false}).check();await page.getByRole('button',{name:'Terbitkan ke perpustakaan'}).click();await page.getByRole('link',{name:'Baca materi yang diterbitkan'}).click();await expect(page.locator('h1')).toHaveText('Latihan pribadi');const url=page.url();await page.reload();await expect(page.locator('h1')).toHaveText('Latihan pribadi');
 await page.getByRole('button',{name:'Edit materi',exact:true}).click();await page.getByLabel('Judul pelajaran',{exact:true}).fill('Latihan diperbarui');await page.getByRole('button',{name:'Simpan perubahan',exact:true}).click();await expect(page.locator('h1')).toHaveText('Latihan diperbarui');
 await page.getByRole('link',{name:'Pengaturan',exact:true}).click();await expect(page.getByLabel('Kode akses',{exact:true})).toHaveCount(0);const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Ekspor JSON'}).click();const download=await downloadEvent;expect(download.suggestedFilename()).toMatch(/^murajaah-.*\.json$/);expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);expect(apiCalls).toBe(0);
 const other=await browser.newContext();const visitor=await other.newPage();await visitor.goto(url);await expect(visitor.locator('h1')).toHaveText('Materi tidak ditemukan');await other.close();
});
test('dirty draft confirms navigation and preserves its saved version',async({page})=>{
 await page.goto(`${base}#/tambah`);await page.getByRole('button',{name:/Materi di subjek yang ada/}).click();await page.getByLabel('Topik',{exact:true}).fill('Draf latihan');await page.getByLabel('Referensi',{exact:true}).fill('Catatan');await page.getByLabel('Teks materi',{exact:false}).fill('Isi draf latihan.');await page.getByRole('button',{name:'Buat draf manual'}).click();await page.getByLabel('Judul pelajaran',{exact:true}).fill('Belum disimpan');page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('link',{name:'Materi',exact:true}).click();await expect(page).toHaveURL(/#\/tambah$/);await page.getByRole('button',{name:'Simpan draf',exact:true}).click();await page.getByRole('link',{name:'Materi',exact:true}).click();await expect(page).toHaveURL(/#\/materi$/);
});
