"use client";
import {useState} from 'react';
import {exportBackup,importBackup,validateBackup,type Backup} from '@/lib/backup';
import {useLibrary} from './library-provider';
export function BackupControls(){
 const {refresh}=useLibrary();const [preview,setPreview]=useState<Backup|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function download(){setBusy(true);setMessage('');try{const data=await exportBackup();const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`murajaah-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Cadangan diunduh. Simpan file di tempat yang aman.');}catch{setMessage('Cadangan belum dapat dibuat. Data lokal tetap tersedia.');}finally{setBusy(false);}}
 async function read(file:File|undefined){if(!file)return;setBusy(true);setPreview(null);setMessage('');try{if(file.size>20*1024*1024)throw new Error('File cadangan maksimal 20 MB.');setPreview(validateBackup(JSON.parse(await file.text())));setMessage('Cadangan valid. Tinjau ringkasan sebelum mengimpor.');}catch(e){setMessage(e instanceof Error&&!(e instanceof SyntaxError)?'Cadangan tidak valid atau relasinya tidak lengkap. Tidak ada data yang diubah.':'File bukan JSON yang valid. Tidak ada data yang diubah.');}finally{setBusy(false);}}
 async function restore(){if(!preview||busy)return;setBusy(true);let restored=false;try{await importBackup(preview);restored=true;setPreview(null);await refresh();setMessage('Cadangan berhasil diimpor. Perpustakaan dan kemajuan diperbarui.');window.dispatchEvent(new Event('murajaah-settings-changed'));}catch{setMessage(restored?'Cadangan sudah diimpor. Muat ulang halaman untuk memperbarui tampilan.':'Impor gagal. Data sebelumnya tetap tersimpan.');}finally{setBusy(false);}}
 return <section className="quiz-panel backup-panel"><h2>Cadangan data</h2><p>Cadangkan materi, draf, dan kemajuan Anda. File tidak menyertakan kode akses atau kunci AI.</p><button className="button" disabled={busy} onClick={()=>void download()}>Ekspor JSON</button><label className="field">Impor cadangan JSON<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{void read(e.target.files?.[0]);e.target.value='';}}/></label>{preview&&<div className="notice"><h3>Tinjau cadangan</h3><p>{preview.subjects.length} subjek · {preview.lessons.length} pelajaran · {preview.questions.length} soal · {preview.attempts.length} jawaban · {preview.notes.length} catatan kajian.</p><p>Impor akan mengganti seluruh materi dan kemajuan pada browser ini. Ekspor data saat ini terlebih dahulu jika ingin menyimpannya.</p><div className="actions"><button className="button" disabled={busy} onClick={()=>void restore()}>Konfirmasi ganti data dan impor</button><button className="text-link plain-button" disabled={busy} onClick={()=>{setPreview(null);setMessage('Impor dibatalkan. Data tidak berubah.');}}>Batalkan impor</button></div></div>}<p role="status" aria-label="Status cadangan" aria-live="polite">{message}</p></section>;
}
