"use client";
import {useState} from 'react';
import {validateDraft,type Draft} from '@/lib/generation';
type Props={draft:Draft;onChange:(draft:Draft)=>void;onSave:()=>Promise<void>;onPublish:(verified:boolean)=>Promise<void>;busy:boolean};
export function DraftEditor({draft,onChange,onSave,onPublish,busy}:Props){
 const [approved,setApproved]=useState(false);const [verified,setVerified]=useState(false);const [error,setError]=useState('');
 function change(next:Draft){setApproved(false);setVerified(false);onChange(next);}
 function lesson(index:number,key:string,value:unknown){change({...draft,data:{...draft.data,lessons:draft.data.lessons.map((l,i)=>i===index?{...l,[key]:value}:l)}});}
 function question(index:number,key:string,value:unknown){change({...draft,data:{...draft.data,questions:draft.data.questions.map((q,i)=>i===index?{...q,[key]:value}:q)}});}
 async function publish(){try{validateDraft(draft.data);if(!approved)throw new Error('Tinjau dan setujui draf terlebih dahulu.');setError('');await onPublish(verified);}catch(e){setError(e instanceof Error?e.message:'Draf belum dapat diterbitkan.');}}
 return <section className="draft-editor"><h2>Tinjau draf</h2><p className="notice">Draf perlu diperiksa dengan sumber atau guru. Persetujuan penerbitan tidak otomatis menjadikan materi terverifikasi. {draft.grounded?'Rujukan berasal dari bahan yang Anda berikan. Bukti pendek di bawah perlu diperiksa, terutama hasil pembacaan foto.':'Materi ini memakai rujukan umum, bukan atribusi isi buku yang disebutkan.'}</p><label className="field">Nama subjek<input value={draft.subject} disabled={!!draft.subjectId} onChange={e=>change({...draft,subject:e.target.value})}/></label><label className="field">Judul topik<input value={draft.topic} onChange={e=>change({...draft,topic:e.target.value})}/></label>
 {draft.data.lessons.map((l,i)=><fieldset className="editor-block" key={i}><legend>Pelajaran {i+1}</legend><label className="field">Judul pelajaran<input value={l.title} onChange={e=>lesson(i,'title',e.target.value)}/></label><label className="field">Penjelasan<textarea rows={5} value={l.explanation} onChange={e=>lesson(i,'explanation',e.target.value)}/></label><h3>Ringkasan materi</h3>{l.rules.map((r,j)=><div key={j}><label className="field">Nama kaidah {j+1}<input value={r.name} onChange={e=>lesson(i,'rules',l.rules.map((item,k)=>k===j?{...item,name:e.target.value}:item))}/></label><label className="field">Ringkasan kaidah {j+1}<textarea value={r.description} onChange={e=>lesson(i,'rules',l.rules.map((item,k)=>k===j?{...item,description:e.target.value}:item))}/></label><button type="button" className="plain-button text-link" disabled={l.rules.length<=1} onClick={()=>lesson(i,'rules',l.rules.filter((_,k)=>k!==j))}>Hapus kaidah {j+1}</button></div>)}<button type="button" className="plain-button text-link" disabled={l.rules.length>=8} onClick={()=>lesson(i,'rules',[...l.rules,{name:'',description:''}])}>Tambah kaidah</button><h3>Contoh Arab dari teks Anda</h3><p className="muted">Tempel sendiri jika diperlukan. AI tidak mengambil ayat dari ingatan. Untuk rujukan ayat, gunakan surah:ayah.</p>{l.examples.map((example,j)=><div key={j}>{(['arabic','transliteration','meaning','note'] as const).map(key=><label className="field" key={key}>{({arabic:'Teks Arab (tempel dari sumber)',transliteration:'Transliterasi',meaning:'Makna',note:'Catatan'})[key]}<input lang={key==='arabic'?'ar':undefined} dir={key==='arabic'?'rtl':undefined} className={key==='arabic'?'arabic':undefined} value={example[key]} onChange={e=>lesson(i,'examples',l.examples.map((item,k)=>k===j?{...item,[key]:e.target.value}:item))}/></label>)}<button type="button" className="plain-button text-link" onClick={()=>lesson(i,'examples',l.examples.filter((_,k)=>k!==j))}>Hapus contoh {j+1}</button></div>)}<button type="button" className="plain-button text-link" disabled={l.examples.length>=4} onClick={()=>lesson(i,'examples',[...l.examples,{arabic:'',transliteration:'',meaning:'',note:''}])}>Tambah contoh dari sumber</button><div className="source"><h3>Rujukan</h3><p>{l.sourceRef.title}</p>{l.sourceRef.url&&<a className="text-link" href={l.sourceRef.url} target="_blank" rel="noopener noreferrer">Buka sumber (tab baru)</a>}<label className="field">Halaman / bab<input value={l.sourceRef.locator} onChange={e=>lesson(i,'sourceRef',{...l.sourceRef,locator:e.target.value})}/></label>{l.evidence&&<p>Bukti pendek: {l.evidence}</p>}</div></fieldset>)}
 <h3>Soal untuk ditinjau</h3>{draft.data.questions.map((q,i)=><fieldset className="editor-block" key={i}><legend>Soal {i+1}</legend><label className="field">Jenis soal<select value={q.type} onChange={e=>question(i,'type',e.target.value)}><option value="multiple-choice">Pilihan ganda</option><option value="true-false">Benar / salah</option><option value="identify-rule">Kenali kaidah</option></select></label><label className="field">Pelajaran terkait<select value={q.lessonIndex} onChange={e=>question(i,'lessonIndex',Number(e.target.value))}>{draft.data.lessons.map((l,j)=><option key={j} value={j}>{l.title}</option>)}</select></label><label className="field">Pertanyaan<textarea value={q.prompt} onChange={e=>question(i,'prompt',e.target.value)}/></label>{q.options.map((option,j)=><label className="field" key={j}>Pilihan {j+1}<input value={option} onChange={e=>question(i,'options',q.options.map((item,k)=>k===j?e.target.value:item))}/></label>)}<label className="field">Jawaban tepat<select value={q.correctIndex} onChange={e=>question(i,'correctIndex',Number(e.target.value))}>{q.options.map((option,j)=><option key={j} value={j}>{j+1}. {option}</option>)}</select></label><label className="field">Penjelasan jawaban<textarea value={q.explanation} onChange={e=>question(i,'explanation',e.target.value)}/></label><p className="muted">Rujukan: {q.sourceRef.title}</p>{q.sourceRef.url&&<a className="text-link" href={q.sourceRef.url} target="_blank" rel="noopener noreferrer">Buka rujukan soal (tab baru)</a>}<label className="field">Halaman / bab soal<input value={q.sourceRef.locator} onChange={e=>question(i,'sourceRef',{...q.sourceRef,locator:e.target.value})}/></label>{q.evidence&&<p>Bukti pendek: {q.evidence}</p>}</fieldset>)}
 <button type="button" className="plain-button text-link" disabled={draft.data.questions.length>=10||busy} onClick={()=>change({...draft,data:{...draft.data,questions:[...draft.data.questions,{lessonIndex:0,type:'multiple-choice',prompt:'',options:['',''],correctIndex:0,explanation:'',sourceRef:draft.data.lessons[0].sourceRef,evidence:''}]}})}>Tambah soal manual</button><p className="muted">{draft.data.questions.length} soal. Materi tanpa soal tetap dapat disimpan untuk dibaca.</p>
 <label className="choice"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Saya sudah meninjau pelajaran, rujukan, dan semua jawaban kuis.</label><label className="choice"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Saya telah memverifikasi materi dengan sumber atau guru; tandai Terverifikasi.</label>{error&&<p role="alert" className="notice">{error}</p>}<div className="actions"><button className="text-link plain-button" disabled={busy} onClick={()=>void onSave()}>Simpan draf</button><button className="button" disabled={busy||!approved} onClick={()=>void publish()}>{busy?'Menyimpan…':'Terbitkan ke perpustakaan'}</button></div></section>;
}
