"use client";
import {useEffect,useState} from 'react';
import {lessonSchema,questionSchema,type Lesson,type Question} from '@/lib/schema';
import {updateLesson,type LessonSnapshot} from '@/lib/lessons';
import {pdfPath} from '@/lib/tuhfatul-athfal';

type Props={snapshot:LessonSnapshot;onSaved:()=>void;onCancel:()=>void};
export function LessonEditor({snapshot,onSaved,onCancel}:Props){
 const [lesson,setLesson]=useState<Lesson>(structuredClone(snapshot.lesson));
 const [questions,setQuestions]=useState<Question[]>(structuredClone(snapshot.questions));
 const [verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const dirty=JSON.stringify(lesson)!==JSON.stringify(snapshot.lesson)||JSON.stringify(questions)!==JSON.stringify(snapshot.questions);
 useEffect(()=>{if(!dirty)return;const guard=(event:BeforeUnloadEvent)=>{event.preventDefault();};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 function changeLesson(next:Lesson){setLesson(next);setVerified(false);}
 function changeQuestion(next:Question,index:number){setQuestions(items=>items.map((q,i)=>i===index?next:q));setVerified(false);}
 async function save(){setBusy(true);setError('');try{
  const status=verified?'verified':'draft';const next=lessonSchema.parse({...lesson,status,sourceRef:{...lesson.sourceRef,url:lesson.sourceRef.url?.trim()||undefined}});
  const nextQuestions=questions.map(q=>questionSchema.parse({...q,status,sourceRef:{...q.sourceRef,url:q.sourceRef.url?.trim()||undefined}}));
  await updateLesson(snapshot,next,nextQuestions);onSaved();
 }catch(e){setError(e instanceof Error&&e.name!=='ZodError'?e.message:'Isian belum valid. Lengkapi judul, penjelasan, kaidah, contoh, dan pilihan jawaban; URL harus http atau https.');}finally{setBusy(false);}}
 return <section className="draft-editor" aria-label="Editor materi"><h2>Edit materi</h2><p className="notice">Perubahan tersimpan di perangkat ini. Status kembali Draf kecuali Anda memverifikasi ulang. Riwayat soal yang diubah/dihapus akan direset; perubahan isi pelajaran menghapus tanda sudah dibaca.</p><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}>
 <label className="field">Judul pelajaran<input required maxLength={2000} value={lesson.title} onChange={e=>changeLesson({...lesson,title:e.target.value})}/></label>
 <label className="field">Penjelasan<textarea required maxLength={2000} rows={5} value={lesson.explanation} onChange={e=>changeLesson({...lesson,explanation:e.target.value})}/></label>
 <h3>Ringkasan materi</h3>{lesson.rules.map((rule,i)=><fieldset key={i} className="editor-block"><legend>Kaidah {i+1}</legend><label className="field">Nama kaidah {i+1}<input required maxLength={2000} value={rule.name} onChange={e=>changeLesson({...lesson,rules:lesson.rules.map((r,j)=>j===i?{...r,name:e.target.value}:r)})}/></label><label className="field">Ringkasan kaidah {i+1}<textarea required maxLength={2000} value={rule.description} onChange={e=>changeLesson({...lesson,rules:lesson.rules.map((r,j)=>j===i?{...r,description:e.target.value}:r)})}/></label><button type="button" className="plain-button text-link" disabled={lesson.rules.length<=1} onClick={()=>changeLesson({...lesson,rules:lesson.rules.filter((_,j)=>j!==i)})}>Hapus kaidah {i+1}</button></fieldset>)}<button type="button" className="plain-button text-link" disabled={lesson.rules.length>=8} onClick={()=>changeLesson({...lesson,rules:[...lesson.rules,{name:'',description:''}]})}>Tambah kaidah</button>
 <h3>Contoh dari sumber</h3>{lesson.examples.map((example,i)=><fieldset key={i} className="editor-block"><legend>Contoh {i+1}</legend>{(['arabic','transliteration','meaning','note'] as const).map(key=><label className="field" key={key}>{({arabic:'Teks Arab',transliteration:'Transliterasi',meaning:'Makna',note:'Catatan'})[key]} {i+1}<textarea required maxLength={2000} lang={key==='arabic'?'ar':undefined} dir={key==='arabic'?'rtl':undefined} className={key==='arabic'?'arabic':undefined} value={example[key]} onChange={e=>changeLesson({...lesson,examples:lesson.examples.map((item,j)=>j===i?{...item,[key]:e.target.value}:item)})}/></label>)}<button type="button" className="plain-button text-link" onClick={()=>changeLesson({...lesson,examples:lesson.examples.filter((_,j)=>j!==i)})}>Hapus contoh {i+1}</button></fieldset>)}<button type="button" className="plain-button text-link" disabled={lesson.examples.length>=4} onClick={()=>changeLesson({...lesson,examples:[...lesson.examples,{arabic:'',transliteration:'',meaning:'',note:''}]})}>Tambah contoh dari sumber</button>
 <h3>Rujukan</h3><label className="field">Judul sumber<input required maxLength={2000} value={lesson.sourceRef.title} onChange={e=>changeLesson({...lesson,sourceRef:{...lesson.sourceRef,title:e.target.value}})}/></label><label className="field">Halaman / bab<input maxLength={160} value={lesson.sourceRef.locator} onChange={e=>changeLesson({...lesson,sourceRef:{...lesson.sourceRef,locator:e.target.value}})}/></label><label className="field">URL sumber (opsional)<input type="url" value={lesson.sourceRef.url??''} onChange={e=>changeLesson({...lesson,sourceRef:{...lesson.sourceRef,url:e.target.value}})}/></label>
 {lesson.sourceRef.document&&<><a className="text-link" href={`${pdfPath}#page=${lesson.sourceRef.pdfPage??1}`} target="_blank" rel="noopener noreferrer">Baca PDF sumber (tab baru)</a><label className="field">Halaman PDF<input type="number" min={1} max={31} required value={lesson.sourceRef.pdfPage??1} onChange={e=>changeLesson({...lesson,sourceRef:{...lesson.sourceRef,pdfPage:Number(e.target.value)}})}/></label></>}
 <h3>Soal terkait ({questions.length})</h3>{questions.map((q,i)=><fieldset className="editor-block" key={q.id}><legend>Soal {i+1}</legend><label className="field">Pertanyaan {i+1}<textarea required maxLength={2000} value={q.prompt} onChange={e=>changeQuestion({...q,prompt:e.target.value},i)}/></label><label className="field">Jenis soal {i+1}<select value={q.type} onChange={e=>changeQuestion({...q,type:e.target.value as Question['type'],...(e.target.value==='true-false'?{options:['Benar','Salah'],correctIndex:0}:{})},i)}><option value="multiple-choice">Pilihan ganda</option><option value="true-false">Benar / salah</option><option value="identify-rule">Kenali kaidah</option></select></label>{q.options.map((option,j)=><label className="field" key={j}>Pilihan {j+1} soal {i+1}<input required maxLength={2000} readOnly={q.type==='true-false'} value={option} onChange={e=>changeQuestion({...q,options:q.options.map((item,k)=>k===j?e.target.value:item)},i)}/></label>)}<label className="field">Jawaban tepat soal {i+1}<select value={q.correctIndex} onChange={e=>changeQuestion({...q,correctIndex:Number(e.target.value)},i)}>{q.options.map((option,j)=><option key={j} value={j}>{j+1}. {option}</option>)}</select></label><label className="field">Penjelasan jawaban {i+1}<textarea required maxLength={2000} value={q.explanation} onChange={e=>changeQuestion({...q,explanation:e.target.value},i)}/></label><label className="field">Judul sumber soal {i+1}<input required maxLength={2000} value={q.sourceRef.title} onChange={e=>changeQuestion({...q,sourceRef:{...q.sourceRef,title:e.target.value}},i)}/></label><label className="field">Halaman / bab soal {i+1}<input maxLength={160} value={q.sourceRef.locator} onChange={e=>changeQuestion({...q,sourceRef:{...q.sourceRef,locator:e.target.value}},i)}/></label><button type="button" className="plain-button text-link" onClick={()=>{setQuestions(items=>items.filter(item=>item.id!==q.id));setVerified(false);}}>Hapus soal {i+1}</button></fieldset>)}
 <button type="button" className="plain-button text-link" onClick={()=>{setQuestions(items=>[...items,{id:crypto.randomUUID(),lessonId:lesson.id,type:'multiple-choice',prompt:'',options:['','',''],correctIndex:0,explanation:'',origin:'manual',status:'draft',sourceRef:{...lesson.sourceRef}}]);setVerified(false);}}>Tambah soal</button>
 <label className="choice"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Saya telah memverifikasi ulang materi, sumber, dan semua jawaban kuis.</label>
 {error&&<p role="alert" className="notice">{error}</p>}<div className="actions"><button className="button" type="submit">{busy?'Menyimpan…':'Simpan perubahan'}</button><button className="plain-button text-link" type="button" onClick={onCancel}>Batal edit</button></div>
 </fieldset></form></section>;
}
