import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('cards isolate a collection, parent deletion validates impact and preserves other content',async({page})=>{
 await page.goto('/materi');await expect(page.getByRole('heading',{name:'Tuhfatul Athfal',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Tahsin',exact:true})).toHaveCount(0);
 await page.evaluate(()=>new Promise<void>((resolve,reject)=>{const request=indexedDB.open('murajaah');request.onsuccess=()=>{const database=request.result;const tx=database.transaction(['subjects','topics','lessons'],'readwrite');tx.objectStore('subjects').put({id:'practice',title:'Koleksi latihan',description:'Koleksi terpisah untuk belajar.',reference:'Sumber latihan'});tx.objectStore('topics').put({id:'practice-topic',subjectId:'practice',title:'Topik latihan',order:99});tx.objectStore('lessons').put({id:'practice-lesson',topicId:'practice-topic',title:'Pelajaran latihan',explanation:'Penjelasan latihan.',rules:[{name:'Kaidah',description:'Ringkasan latihan.'}],examples:[],origin:'manual',status:'draft',sourceRef:{title:'Sumber latihan',locator:'Bab latihan'}});tx.oncomplete=()=>{database.close();resolve();};tx.onerror=()=>reject(tx.error);};request.onerror=()=>reject(request.error);}));
 await page.reload();await page.getByRole('link',{name:/MATERI BELAJAR Koleksi latihan/}).click();await expect(page.locator('h1')).toHaveText('Koleksi latihan');await expect(page.getByRole('link',{name:/^Pelajaran latihan/})).toBeVisible();await expect(page.getByRole('link',{name:/^Nun Sakinah/})).toHaveCount(0);
 await page.getByRole('button',{name:'Hapus seluruh koleksi'}).click();const dialog=page.getByRole('dialog',{name:'Konfirmasi penghapusan'});await expect(dialog).toContainText('1 topik dan 1 pelajaran');await expect(page.getByRole('button',{name:'Hapus data terpilih'})).toBeDisabled();expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);await page.getByRole('textbox',{name:'Ketik HAPUS untuk konfirmasi'}).fill('hapus');await expect(page.getByRole('button',{name:'Hapus data terpilih'})).toBeDisabled();await page.getByRole('button',{name:'Batal hapus'}).click();await page.reload();await expect(page.locator('h1')).toHaveText('Koleksi latihan');
 await page.getByRole('button',{name:'Hapus seluruh koleksi'}).click();await page.getByRole('textbox',{name:'Ketik HAPUS untuk konfirmasi'}).fill('HAPUS');await page.getByRole('button',{name:'Hapus data terpilih'}).click();await expect(page).toHaveURL(/\/materi$/);await page.reload();await expect(page.getByRole('heading',{name:'Koleksi latihan',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Tuhfatul Athfal',exact:true})).toBeVisible();
});
test('selective deletion and reading reset are explicit and persist after reload',async({page})=>{
 await page.goto('/materi/tuhfah-pengantar');await page.getByRole('button',{name:'Tandai sudah dibaca'}).click();await page.getByRole('link',{name:'Kembali ke koleksi'}).click();await expect(page.getByText('1 dari 18 pelajaran dibaca',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Reset progres koleksi'}).click();await page.getByRole('button',{name:'Batal reset'}).click();await expect(page.getByText('1 dari 18 pelajaran dibaca',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Reset progres koleksi'}).click();expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);await page.getByRole('button',{name:'Ya, reset progres'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.getByText('Progres berhasil direset. Materi dan soal tetap tersimpan.')).toBeVisible();await page.reload();await expect(page.getByText('0 dari 18 pelajaran dibaca',{exact:true})).toBeVisible();
 await page.getByRole('checkbox',{name:'Pilih Mengenal Tuhfatul Athfal',exact:true}).check();await page.getByRole('checkbox',{name:'Pilih Nun Sakinah dan Tanwin',exact:true}).check();await page.getByRole('button',{name:'Hapus pelajaran terpilih (2)'}).click();await expect(page.getByRole('dialog')).toContainText('0 topik dan 2 pelajaran');await expect(page.getByRole('dialog')).toContainText('4 soal');await page.getByRole('textbox',{name:'Ketik HAPUS untuk konfirmasi'}).fill('HAPUS');await page.getByRole('button',{name:'Hapus data terpilih'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await page.reload();await expect(page.getByRole('link',{name:/^Nun Sakinah/})).toHaveCount(0);await expect(page.getByText('0 dari 16 pelajaran dibaca',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:/^Mim Sakinah/})).toBeVisible();
});
test('home shows ticking local time and both calendars, with a global reset control',async({page})=>{
 await page.goto('/');await expect(page.locator('.clock-time')).toHaveText(/\d{2}[.:]\d{2}[.:]\d{2}/);await expect(page.getByLabel('Tanggal Masehi')).toContainText(/\d{4}/);await expect(page.getByLabel('Tanggal Hijriah')).toContainText(/Hijriah \(perhitungan\)/);await expect(page.getByRole('button',{name:'Reset semua progres'})).toBeVisible();const before=await page.locator('.clock-time').innerText();await expect(page.locator('.clock-time')).not.toHaveText(before,{timeout:3000});
});
