import {z} from 'zod';
import {validateBackup,type Backup} from './backup';
export const driveScope='https://www.googleapis.com/auth/drive.appdata';
export const maxBackupBytes=20*1024*1024;
export const clientIdSchema=z.string().trim().regex(/^\d+-[a-zA-Z0-9_-]+\.apps\.googleusercontent\.com$/,'Gunakan OAuth Client ID aplikasi web Google, bukan Client Secret.');
const driveFileSchema=z.object({id:z.string().regex(/^[a-zA-Z0-9_-]+$/).max(200),name:z.string().max(500),modifiedTime:z.string().datetime(),size:z.string().regex(/^\d+$/).optional()});
const listSchema=z.object({files:z.array(driveFileSchema).max(100),nextPageToken:z.string().max(2000).optional()});
export type DriveFile=z.infer<typeof driveFileSchema>;
export type GoogleToken={access_token?:string;expires_in?:number;scope?:string;error?:string};
type OAuthClient={requestAccessToken:(options:{prompt:string})=>void};
type GoogleIdentity={accounts:{oauth2:{initTokenClient:(options:{client_id:string;scope:string;include_granted_scopes:boolean;callback:(reply:GoogleToken)=>void;error_callback:()=>void})=>OAuthClient;revoke:(token:string,callback:()=>void)=>void}}};
function identity(){return (window as Window & {google?:GoogleIdentity}).google;}
let scriptPromise:Promise<void>|undefined;
let token='';let expiresAt=0;
export function hasDriveSession(){return !!token&&Date.now()<expiresAt;}
export function clearDriveSession(){token='';expiresAt=0;}
export function acceptDriveToken(reply:GoogleToken){clearDriveSession();if(reply.error||!reply.access_token||!reply.scope?.split(' ').includes(driveScope)||!reply.expires_in||reply.expires_in<=0)throw new Error('Google belum memberikan izin cadangan aplikasi. Data lokal tetap tersedia.');token=reply.access_token;expiresAt=Date.now()+Math.min(reply.expires_in,3600)*1000-30000;}
export async function prepareGoogle(){if(identity())return;if(!navigator.onLine)throw new Error('Hubungkan internet untuk menyiapkan Google Drive. Ekspor JSON tetap bisa digunakan offline.');if(!scriptPromise)scriptPromise=new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;const timer=setTimeout(()=>{script.remove();reject(new Error('Google belum dapat dimuat. Periksa koneksi internet lalu coba lagi.'));},15000);script.onload=()=>{clearTimeout(timer);if(identity())resolve();else reject(new Error('Koneksi Google belum tersedia.'));};script.onerror=()=>{clearTimeout(timer);script.remove();reject(new Error('Google belum dapat dimuat. Periksa koneksi internet.'));};document.head.append(script);}).catch(error=>{scriptPromise=undefined;throw error;});await scriptPromise;}
// Called directly from a user click; no popup or Google request on page load.
export function connectDrive(clientId:string,onConnected:()=>void,onError:(message:string)=>void){const google=identity();if(!google)throw new Error('Siapkan koneksi Google dahulu.');const id=clientIdSchema.parse(clientId);clearDriveSession();const client=google.accounts.oauth2.initTokenClient({client_id:id,scope:driveScope,include_granted_scopes:false,callback:reply=>{try{acceptDriveToken(reply);onConnected();}catch(error){onError(error instanceof Error?error.message:'Izin Google belum diberikan.');}},error_callback:()=>onError('Jendela Google ditutup atau diblokir. Izinkan popup lalu hubungkan kembali.')});client.requestAccessToken({prompt:'select_account'});}
export function disconnectDrive(){const previous=token;clearDriveSession();if(previous)identity()?.accounts.oauth2.revoke(previous,()=>{});}
async function request(path:string,init:RequestInit={}){if(!hasDriveSession()){clearDriveSession();throw new Error('Sesi Google berakhir. Hubungkan Google Drive kembali.');}let response:Response;try{response=await fetch(`https://www.googleapis.com/${path}`,{...init,headers:{...init.headers,Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(30000),redirect:'error'});}catch{throw new Error('Koneksi Google Drive terputus atau terlalu lama. Periksa internet; data lokal tetap tersedia.');}if(!response.ok){if(response.status===401){clearDriveSession();throw new Error('Sesi Google berakhir. Hubungkan kembali.');}if(response.status===403||response.status===429)throw new Error('Izin atau kuota Google Drive tidak tersedia. Tidak ada retry otomatis; gunakan cadangan JSON.');throw new Error('Google Drive belum dapat diakses. Data lokal tetap tersedia.');}return response;}
export async function listDriveBackups(){const query=new URLSearchParams({spaces:'appDataFolder',q:"trashed = false and appProperties has { key='murajaahBackup' and value='v1' }",fields:'files(id,name,modifiedTime,size),nextPageToken',orderBy:'modifiedTime desc',pageSize:'100'});const response=await request(`drive/v3/files?${query}`);return listSchema.parse(await response.json());}
export async function uploadDriveBackup(raw:Backup){const data=validateBackup(raw);const json=JSON.stringify(data);if(new Blob([json]).size>maxBackupBytes)throw new Error('Cadangan maksimal 20 MB.');const name=`murajaah-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;const boundary=`murajaah_${crypto.randomUUID().replaceAll('-','')}`;const metadata={name,parents:['appDataFolder'],mimeType:'application/json',appProperties:{murajaahBackup:'v1'}};const body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n`,JSON.stringify(metadata),`\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n`,json,`\r\n--${boundary}--\r\n`],{type:`multipart/related; boundary=${boundary}`});const response=await request('upload/drive/v3/files?uploadType=multipart&fields=id,name,modifiedTime,size',{method:'POST',body,headers:{'Content-Type':body.type}});return driveFileSchema.parse(await response.json());}
export async function downloadDriveBackup(file:DriveFile){const checked=driveFileSchema.parse(file);if(checked.size&&Number(checked.size)>maxBackupBytes)throw new Error('Cadangan maksimal 20 MB.');const response=await request(`drive/v3/files/${encodeURIComponent(checked.id)}?alt=media`);if(Number(response.headers.get('content-length'))>maxBackupBytes){await response.body?.cancel();throw new Error('Cadangan maksimal 20 MB.');}const reader=response.body?.getReader();if(!reader)throw new Error('Cadangan kosong.');let total=0;const chunks:Uint8Array<ArrayBuffer>[]=[];try{for(;;){const result=await reader.read();if(result.done)break;total+=result.value.byteLength;if(total>maxBackupBytes){await reader.cancel();throw new Error('Cadangan maksimal 20 MB.');}chunks.push(result.value);}const json=await new Blob(chunks).text();return validateBackup(JSON.parse(json));}catch(error){if(error instanceof SyntaxError||error instanceof z.ZodError)throw new Error('Cadangan Google Drive tidak valid. Data lokal tidak diubah.');throw error;}finally{reader.releaseLock();}}
