"use client";
import {ArabicText} from '@/components/arabic-text';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useLibrary,LibraryState} from '@/components/library-provider';
import {db} from '@/lib/db';
import type {Attempt,Question} from '@/lib/schema';
import {inScope,latestAttempt,nextBox,pickQuestions} from '@/lib/quiz';
type Answer={question:Question;selected:number;correct:boolean};
export default function Quiz(){
 const {subjects,topics,lessons,loading,error}=useLibrary();
 const [subject,setSubject]=useState('tahsin');const [selectedTopics,setSelectedTopics]=useState<string[]>([]);const [count,setCount]=useState(5);
 const [pool,setPool]=useState<Question[]>([]);const [attempts,setAttempts]=useState<Attempt[]>([]);const [ready,setReady]=useState(false);const [verifiedOnly,setVerifiedOnly]=useState(false);
 const [session,setSession]=useState<Question[]>([]);const [answers,setAnswers]=useState<Answer[]>([]);const [selected,setSelected]=useState<number|null>(null);const [feedback,setFeedback]=useState<Answer|null>(null);const [finished,setFinished]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const lock=useRef(false);const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(loading||error)return;let alive=true;Promise.all([db.questions.toArray(),db.attempts.toArray(),db.meta.get('verified-only')]).then(([q,a,m])=>{if(alive){setPool(q);setAttempts(a);setVerifiedOnly(m?.value==='true');setReady(true);}}).catch(()=>setMessage('Data kuis belum dapat dibaca. Muat ulang untuk mencoba lagi.'));return()=>{alive=false;};},[loading,error]);
 useEffect(()=>{if(session.length)heading.current?.focus();},[session,answers.length,finished]);
 const effectiveSubject=subjects.some(s=>s.id===subject)?subject:subjects[0]?.id??'';
 const scoped=inScope(pool,lessons,topics,effectiveSubject,selectedTopics,verifiedOnly);const question=session[answers.length];
 function start(source:Question[]=scoped,size=count){setSession(pickQuestions(source,size,attempts));setAnswers([]);setSelected(null);setFeedback(null);setFinished(false);setMessage('');}
 async function submit(){if(!question||selected===null||lock.current)return;lock.current=true;setSaving(true);setMessage('');const correct=selected===question.correctIndex;const attempt:Attempt={id:crypto.randomUUID(),questionId:question.id,correct,answeredAt:Date.now(),box:nextBox(latestAttempt(question.id,attempts),correct)};try{await db.attempts.add(attempt);setAttempts(a=>[...a,attempt]);setFeedback({question,selected,correct});}catch{setMessage('Jawaban belum tersimpan. Silakan coba lagi.');}finally{lock.current=false;setSaving(false);}}
 function advance(){if(!feedback)return;setAnswers(a=>[...a,feedback]);setFeedback(null);setSelected(null);if(answers.length+1===session.length)setFinished(true);}
 if(loading||error)return <LibraryState/>;
 const wrong=answers.filter(a=>!a.correct);
 return <><header className="page-head"><p className="eyebrow">ULANGI PEMAHAMAN</p><h1>Kuis</h1><p>Bukan tentang cepat menjawab. Beri ruang untuk memahami kembali.</p></header>
 {message&&<p role="alert" className="notice">{message}</p>}
 {!session.length?<section className="quiz-panel"><h2>Atur sesi belajar</h2><label className="field">Subjek<select value={effectiveSubject} onChange={e=>{setSubject(e.target.value);setSelectedTopics([]);}}>{subjects.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><fieldset><legend>Topik</legend><p className="muted">Tanpa pilihan, semua topik dalam subjek akan digunakan.</p>{topics.filter(t=>t.subjectId===effectiveSubject&&lessons.some(l=>l.topicId===t.id)).map(t=><label className="choice" key={t.id}><input type="checkbox" checked={selectedTopics.includes(t.id)} onChange={e=>setSelectedTopics(ids=>e.target.checked?[...ids,t.id]:ids.filter(id=>id!==t.id))}/>{t.title}</label>)}</fieldset><label className="field">Jumlah soal<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[5,10,20].map(n=><option key={n} value={n}>{n} soal</option>)}</select></label><p className="notice">{ready?`${scoped.length} soal tersedia. Sesi ini berisi ${Math.min(count,scoped.length)} soal tanpa pengulangan.`:'Menyiapkan soal…'} {verifiedOnly?'Hanya materi terverifikasi digunakan.':'Soal draf disertakan; tinjau penjelasannya dengan buku atau guru.'}</p>{ready&&!scoped.length&&<p>Belum ada soal untuk pilihan ini. Pilih topik lain atau ubah filter materi terverifikasi.</p>}<button className="button" disabled={!ready||!scoped.length} onClick={()=>start()}>Mulai kuis</button></section>
 :finished?<section className="quiz-panel"><h2 tabIndex={-1} ref={heading}>Sesi selesai</h2><p className="score">{answers.filter(a=>a.correct).length} / {session.length}</p><p>{wrong.length?'Beberapa kaidah dapat Anda pelajari kembali.':'Semua jawaban tepat. Tetap luangkan waktu untuk meninjau kaidahnya.'}</p><h3 className="result-title">Jawaban yang perlu ditinjau</h3>{wrong.length?wrong.map(a=><div className="result-item" key={a.question.id}><h4><ArabicText text={a.question.prompt}/></h4><p>Jawaban Anda: {a.question.options[a.selected]}</p><p>Jawaban tepat: {a.question.options[a.question.correctIndex]}</p><p><ArabicText text={a.question.explanation}/></p><Link className="text-link" href={`/materi/${a.question.lessonId}`}>Pelajari materi</Link></div>):<p>Tidak ada jawaban yang salah.</p>}<div className="actions">{wrong.length>0&&<button className="button" onClick={()=>start(wrong.map(a=>a.question),wrong.length)}>Ulangi yang salah</button>}<button className="text-link" onClick={()=>{setSession([]);setFinished(false);}}>Atur sesi baru</button></div></section>
 :question?<section className="quiz-panel"><p className="eyebrow">SOAL {answers.length+1} DARI {session.length}</p>{question.status==='draft'&&<span className="badge">Draf</span>}<h2 ref={heading} tabIndex={-1} className="question-heading">{question.type==='identify-rule'&&/[\u0600-\u06ff]/.test(question.prompt)?<span lang="ar" dir="rtl" className="arabic">{question.prompt.split(' menunjukkan')[0]}</span>:question.prompt}</h2>{question.type==='identify-rule'&&/[\u0600-\u06ff]/.test(question.prompt)&&<p>Kenali hukum pada diagram huruf ini (bukan kutipan ayat).</p>}<fieldset disabled={!!feedback||saving}><legend>Pilih satu jawaban</legend>{question.options.map((option,i)=><label className="choice" key={`${question.id}-${i}`}><input type="radio" name="answer" value={i} checked={selected===i} onChange={()=>setSelected(i)}/><ArabicText text={option}/></label>)}</fieldset><div aria-live="polite" aria-atomic="true">{feedback&&<div className="notice feedback" data-correct={feedback.correct}><h3>{feedback.correct?'✓ Jawaban tepat':'× Jawaban belum tepat'}</h3>{!feedback.correct&&<p>Jawaban tepat: {question.options[question.correctIndex]}</p>}<p><ArabicText text={question.explanation}/></p><Link className="text-link" href={`/materi/${question.lessonId}`} target="_blank" rel="noopener">Pelajari materi (tab baru)</Link></div>}</div>{feedback?<button className="button" onClick={advance}>{answers.length+1===session.length?'Lihat hasil':'Soal berikutnya'}</button>:<button className="button" disabled={selected===null||saving} onClick={submit}>{saving?'Menyimpan…':'Periksa jawaban'}</button>}</section>:null}
 </>;
}
