"use client";
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {useLibrary,LibraryState} from '@/components/library-provider';
import {DraftEditor} from '@/components/draft-editor';
import {replySchema,generationInputSchema,validateDraft,type Draft} from '@/lib/generation';
import {listDrafts,publishDraft,saveDraft} from '@/lib/drafts';
import {downscalePhoto} from '@/lib/photos';
const publicEdition=process.env.NEXT_PUBLIC_PUBLIC_EDITION==='true';
export default function Add(){
 const {subjects,loading,error,refresh}=useLibrary();
 const [subjectId,setSubjectId]=useState('tuhfatul-athfal');const [subject,setSubject]=useState('');const [topic,setTopic]=useState('');const [reference,setReference]=useState('');const [locator,setLocator]=useState('');const [text,setText]=useState('');const [photos,setPhotos]=useState<{name:string;data:string}[]>([]);
 const effectiveSubjectId=subjects.some(s=>s.id===subjectId)?subjectId:subjectId?subjects[0]?.id??'':'';
 const [draft,setDraft]=useState<Draft|null>(null);const [saved,setSaved]=useState<Draft[]>([]);const [dirty,setDirty]=useState(false);const [busy,setBusy]=useState(false);const [processing,setProcessing]=useState(false);const [message,setMessage]=useState('');const [published,setPublished]=useState('');const guard=useRef(false);const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(loading||error)return;listDrafts().then(setSaved).catch(()=>setMessage('Draf tersimpan belum dapat dibaca.'));},[loading,error]);
 useEffect(()=>{
  function warn(event:BeforeUnloadEvent){if(dirty){event.preventDefault();event.returnValue='';}}
  function navigate(event:MouseEvent){const anchor=event.target instanceof Element?event.target.closest('a'):null;if(!dirty||!anchor||anchor.target==='_blank'||anchor.origin!==location.origin||(anchor.getAttribute('href')?.startsWith('#')&&!anchor.getAttribute('href')?.startsWith('#/')))return;if(!window.confirm('Perubahan draf belum disimpan. Tinggalkan halaman dan abaikan perubahan?')){event.preventDefault();event.stopPropagation();}else setDirty(false);}
  window.addEventListener('beforeunload',warn);document.addEventListener('click',navigate,true);return()=>{window.removeEventListener('beforeunload',warn);document.removeEventListener('click',navigate,true);};
 },[dirty]);
 const draftId=draft?.id;
 useEffect(()=>{if(draftId)heading.current?.focus();},[draftId]);
 async function addPhotos(files:FileList|null){if(!files)return;setProcessing(true);setMessage('');try{if(photos.length+files.length>4)throw new Error('Maksimal empat foto per draf.');const converted=await Promise.all(Array.from(files).map(async file=>({name:file.name,data:await downscalePhoto(file)})));setPhotos(current=>[...current,...converted]);}catch(e){setMessage(e instanceof Error?e.message:'Foto belum dapat diproses.');}finally{setProcessing(false);}}
 async function generate(){if(guard.current)return;setMessage('');setPublished('');let input;
 try{if(publicEdition){
  const manual=generationInputSchema.parse({subject:effectiveSubjectId?subjects.find(s=>s.id===effectiveSubjectId)?.title:subject,topic,reference,locator,suppliedText:text,photos:[]});
  if(!manual.suppliedText.trim()||manual.suppliedText.length>2000)throw new Error('Isi teks materi antara 1–2.000 karakter untuk membuat draf manual.');
  const next:Draft={id:crypto.randomUUID(),subjectId:effectiveSubjectId,subject:manual.subject,topic:manual.topic,grounded:true,origin:'manual',createdAt:Date.now(),data:{lessons:[{title:manual.topic,explanation:manual.suppliedText,rules:[{name:'Catatan utama',description:manual.suppliedText}],examples:[],sourceRef:{title:manual.reference,locator:manual.locator,url:''},evidence:''}],questions:[{lessonIndex:0,type:'multiple-choice',prompt:'Materi ini membahas topik apa?',options:[manual.topic,`Bukan ${manual.topic}`],correctIndex:0,explanation:manual.topic,sourceRef:{title:manual.reference,locator:manual.locator,url:''},evidence:''}]}};
  guard.current=true;setBusy(true);await saveDraft(next);setDraft(next);setDirty(false);setSaved(await listDrafts());setMessage('Draf manual tersimpan. Tinjau materi dan ubah soal agar sesuai sebelum menerbitkan.');return;
 }const code=localStorage.getItem('murajaah-access-code');if(!code)throw new Error('Simpan kode akses di Pengaturan terlebih dahulu.');input=generationInputSchema.parse({subject:effectiveSubjectId?subjects.find(s=>s.id===effectiveSubjectId)?.title:subject,topic,reference,locator,suppliedText:text,photos:photos.map(p=>p.data)});guard.current=true;setBusy(true);
  const response=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json','x-access-code':code},body:JSON.stringify(input),signal:AbortSignal.timeout(360000)});
  const raw:unknown=await response.json();if(!response.ok){const failure=z.object({error:z.string()}).safeParse(raw);throw new Error(failure.success?failure.data.error:'Draf belum dapat dibuat.');}
  const result=replySchema.parse(raw);validateDraft(result.data);const next:Draft={id:crypto.randomUUID(),subjectId:effectiveSubjectId,subject:input.subject,topic:input.topic,grounded:result.grounded,data:result.data,createdAt:Date.now()};
  // Keep generated work in memory even if IndexedDB is temporarily unavailable.
  setDraft(next);setDirty(true);await saveDraft(next);setDirty(false);setSaved(await listDrafts());setMessage('Draf tersimpan di perangkat ini. Tinjau sebelum menerbitkan.');
 }catch(e){setMessage(e instanceof z.ZodError?'Lengkapi topik, subjek, dan referensi; periksa format materi.':e instanceof Error?e.message:'Draf belum dapat dibuat.');}finally{guard.current=false;setBusy(false);}}
 async function save(){if(!draft)return;setBusy(true);try{await saveDraft(draft);setDirty(false);setSaved(await listDrafts());setMessage('Perubahan draf tersimpan.');}catch{setMessage('Draf belum tersimpan. Periksa semua kolom, relasi soal, dan jawaban.');}finally{setBusy(false);}}
 async function publish(verified:boolean){if(!draft||guard.current)return;guard.current=true;setBusy(true);try{const id=await publishDraft(draft,verified);setPublished(id);setDraft(null);setDirty(false);setMessage('Materi diterbitkan ke perpustakaan lokal.');await refresh();setSaved(await listDrafts());}catch(e){setMessage(e instanceof Error?e.message:'Materi belum dapat diterbitkan.');}finally{guard.current=false;setBusy(false);}}
 function openDraft(next:Draft){if(dirty&&!window.confirm('Perubahan belum disimpan. Buka draf lain dan abaikan perubahan?'))return;setDraft(next);setDirty(false);setPublished('');setMessage('');}
 if(loading||error)return <LibraryState/>;
 return <><header className="page-head"><p className="eyebrow">PERLUAS PERPUSTAKAAN</p><h1>Tambah materi</h1><p>{publicEdition?'Tambahkan materi sendiri beserta rujukannya. Tinjau draf dan soal sebelum menerbitkan.':'Berikan topik dan rujukan. Tinjau draf sebelum menjadikannya bahan belajar.'}</p>{publicEdition&&<p className="notice">Versi publik mendukung tambah materi manual secara gratis. Pembuatan dengan AI tersedia pada aplikasi lokal dengan Ollama; versi ini tidak menghubungi AI berbayar.</p>}</header><div role="status" aria-live="polite">{message&&<p className="notice">{message}</p>}{busy&&<p>Mengolah materi… AI lokal dapat memerlukan beberapa menit. Biarkan halaman ini terbuka.</p>}</div>{published&&<Link className="button" href={`/materi/${published}`}>Baca materi yang diterbitkan</Link>}
 {saved.length>0&&<section className="saved-drafts"><h2>Draf tersimpan</h2>{saved.map(d=><button className="choice plain-button" key={d.id} disabled={busy} onClick={()=>openDraft(d)}>{d.topic} · {d.subject}</button>)}</section>}
 {draft?<><h2 ref={heading} tabIndex={-1} className="review-heading">Draf: {draft.topic}</h2><DraftEditor key={draft.id} draft={draft} onChange={next=>{setDraft(next);setDirty(true);}} onSave={save} onPublish={publish} busy={busy}/><button className="text-link plain-button" disabled={busy} onClick={()=>{if(!dirty||window.confirm('Perubahan belum disimpan. Kembali dan abaikan perubahan?')){setDraft(null);setDirty(false);}}}>Kembali ke formulir</button></>
 :<form className="quiz-panel" onSubmit={event=>{event.preventDefault();void generate();}}><h2>Bahan belajar</h2><fieldset disabled={busy}><label className="field">Subjek<select value={effectiveSubjectId} onChange={e=>setSubjectId(e.target.value)}>{subjects.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}<option value="">Subjek baru</option></select></label>{!effectiveSubjectId&&<label className="field">Nama subjek baru<input required maxLength={120} value={subject} onChange={e=>setSubject(e.target.value)}/></label>}<label className="field">Topik<input required maxLength={160} value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Contoh: Hukum mad dasar"/></label><label className="field">Referensi<input required maxLength={1000} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Judul buku, URL, atau keterangan sumber"/></label><label className="field">Halaman / bab (opsional)<input maxLength={160} value={locator} onChange={e=>setLocator(e.target.value)} placeholder="Isi hanya jika Anda mengetahuinya"/></label><label className="field">{publicEdition?'Teks materi (wajib, maksimal 2.000 karakter)':'Teks sumber (opsional)'}<textarea required={publicEdition} rows={6} maxLength={publicEdition?2000:16000} value={text} onChange={e=>setText(e.target.value)} placeholder="Tempel bagian yang ingin Anda pelajari"/></label>{!publicEdition&&<label className="field">Foto halaman (opsional, maksimal 4)<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={processing} onChange={e=>{void addPhotos(e.target.files);e.target.value='';}}/></label>}{processing&&<p role="status">Menyiapkan foto…</p>}<div className="photo-grid">{photos.map((photo,i)=><div key={`${photo.name}-${i}`}><div className="photo-preview"><Image src={photo.data} fill sizes="(max-width: 768px) 50vw, 240px" alt={`Pratinjau halaman ${i+1}: ${photo.name}`} unoptimized/></div><button type="button" className="text-link plain-button" onClick={()=>setPhotos(current=>current.filter((_,j)=>j!==i))}>Hapus foto {i+1}</button></div>)}</div>{!publicEdition&&<><p className="notice">Teks dan foto diproses oleh AI lokal pada perangkat yang menjalankan aplikasi saat Anda memilih Buat draf. Dengan bahan sumber, draf hanya boleh merangkum bahan itu. Tanpa bahan sumber, draf memakai rujukan umum dari riset Wikipedia gratis; judul buku bukan bukti bahwa AI mengakses buku tersebut.</p><Link className="text-link" href="/pengaturan">Atur kode akses</Link><br/></>}<button className="button" disabled={busy||processing} type="submit">{publicEdition?'Buat draf manual':'Buat draf'}</button></fieldset></form>}</>;
}
