"use client";
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {useLibrary,LibraryState} from '@/components/library-provider';
import {DraftEditor} from '@/components/draft-editor';
import {FlowHeader} from '@/components/flow-header';
import {Icon} from '@/components/icon';
import {useUnsaved} from '@/components/use-unsaved';
import {replySchema,generationInputSchema,validateDraft,type Draft} from '@/lib/generation';
import {listDrafts,publishDraft,saveDraft} from '@/lib/drafts';
import {manualDraft} from '@/lib/material-input';
import {extractPdf} from '@/lib/pdf-import';
import {generateOnDevice,deviceModels} from '@/lib/device-ai';
import {downscalePhoto} from '@/lib/photos';
import {db} from '@/lib/db';
const publicEdition=process.env.NEXT_PUBLIC_PUBLIC_EDITION==='true';
export default function Add(){
 const {subjects,loading,error,refresh}=useLibrary();const [step,setStep]=useState(0);const [destination,setDestination]=useState<'new'|'existing'|null>(null);const [subjectId,setSubjectId]=useState('');const [subject,setSubject]=useState('');const [topic,setTopic]=useState('');const [reference,setReference]=useState('');const [locator,setLocator]=useState('');const [text,setText]=useState('');const [source,setSource]=useState<'text'|'pdf'|'photo'>('text');const [photos,setPhotos]=useState<{name:string;data:string}[]>([]);
 const [pdf,setPdf]=useState<File|null>(null),[from,setFrom]=useState(1),[to,setTo]=useState(1);const [draft,setDraft]=useState<Draft|null>(null),[saved,setSaved]=useState<Draft[]>([]),[dirty,setDirty]=useState(false),[formDirty,setFormDirty]=useState(false),[busy,setBusy]=useState(false),[processing,setProcessing]=useState(false),[message,setMessage]=useState(''),[progress,setProgress]=useState(''),[published,setPublished]=useState('');const [method,setMethod]=useState<'manual'|'browser'|'ollama'>('manual'),[model,setModel]=useState(deviceModels[0].id);const guard=useRef(false),abort=useRef<AbortController|null>(null),heading=useRef<HTMLHeadingElement>(null);
 const effectiveSubjectId=destination==='existing'?subjectId:'';useUnsaved(dirty||formDirty);
 useEffect(()=>{if(loading||error)return;listDrafts().then(setSaved).catch(()=>setMessage('Draf tersimpan belum dapat dibaca.'));const noteId=sessionStorage.getItem('murajaah-note-source');if(noteId){db.notes.get(noteId).then(note=>{if(note){setTopic(note.title);setReference(note.reference||[note.speaker,note.title,note.date].filter(Boolean).join(' · '));setText(note.content);setFormDirty(true);setMessage('Catatan kajian sudah diisi sebagai bahan. Pilih tujuan materi untuk melanjutkan.');sessionStorage.removeItem('murajaah-note-source');}}).catch(()=>setMessage('Catatan belum dapat dibaca.'));}},[loading,error]);
 useEffect(()=>{if(step>0)heading.current?.focus();},[step]);
 function edit(action:()=>void){action();setFormDirty(true);}
 function back(){if(busy||processing)return;if(step===2){if(dirty&&!window.confirm('Draf memiliki perubahan yang belum disimpan. Kembali dan abaikan perubahan?'))return;setDraft(null);setDirty(false);setStep(1);}else setStep(0);setMessage('');}
 async function readPdf(){if(!pdf)return;setProcessing(true);setMessage('');try{const result=await extractPdf(pdf,from,to,setProgress);setText(result.pages.map(page=>`[Halaman ${page.page}]\n${page.text}`).join('\n\n'));setReference(pdf.name.replace(/\.pdf$/i,''));setLocator(`PDF hlm. ${from}–${to} dari ${result.total}`);if(!topic)setTopic(pdf.name.replace(/\.pdf$/i,''));setFormDirty(true);setMessage('Teks PDF siap. Periksa hasilnya sebelum membuat materi. File diproses di perangkat Anda.');}catch(error){setMessage(error instanceof Error?error.message:'PDF belum dapat dibaca.');}finally{setProcessing(false);setProgress('');}}
 async function addPhotos(files:FileList|null){if(!files)return;setProcessing(true);try{if(photos.length+files.length>4)throw new Error('Maksimal empat foto.');const next=await Promise.all(Array.from(files).map(async file=>({name:file.name,data:await downscalePhoto(file)})));setPhotos(current=>[...current,...next]);setFormDirty(true);}catch(error){setMessage(error instanceof Error?error.message:'Foto belum dapat dibaca.');}finally{setProcessing(false);}}
 async function generate(){if(guard.current||processing)return;guard.current=true;setBusy(true);setMessage('');setPublished('');abort.current=new AbortController();
  try{const title=destination==='existing'?subjects.find(item=>item.id===subjectId)?.title:subject;if(!title)throw new Error('Pilih atau isi nama subjek.');let next:Draft;
   if(method==='manual'){next=manualDraft({subjectId:effectiveSubjectId,subject:title,topic,reference,locator,text});}
   else{const input=generationInputSchema.parse({subject:title,topic,reference,locator,suppliedText:text,photos:source==='photo'?photos.map(photo=>photo.data):[]});let data;
    if(method==='browser')data=await generateOnDevice(input,model,setProgress,abort.current.signal);
    else{const code=localStorage.getItem('murajaah-access-code');if(!code)throw new Error('Simpan kode akses AI lokal di Pengaturan dahulu.');setProgress('AI lokal membaca bahan dan menyusun draf…');const response=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json','x-access-code':code},body:JSON.stringify(input),signal:abort.current.signal});const raw:unknown=await response.json();if(!response.ok){const failure=z.object({error:z.string()}).safeParse(raw);throw new Error(failure.success?failure.data.error:'Draf AI belum dapat dibuat.');}data=replySchema.parse(raw).data;validateDraft(data);}
    next={id:crypto.randomUUID(),subjectId:effectiveSubjectId,subject:title,topic,grounded:!!(input.suppliedText||input.photos.length),origin:'ai',createdAt:Date.now(),data};
   }
   if(abort.current.signal.aborted)throw new Error('Proses dibatalkan.');await saveDraft(next);setDraft(next);setDirty(false);setFormDirty(false);setStep(2);setSaved(await listDrafts());setMessage('Draf tersimpan. Tinjau materi dan soal sebelum menerbitkan.');
  }catch(error){setMessage(error instanceof z.ZodError?'Lengkapi nama subjek, topik, rujukan, dan bahan. AI maksimal 16.000 karakter; pilih halaman lebih sedikit untuk bahan panjang.':error instanceof Error?error.message:'Materi belum dapat dibuat.');}finally{guard.current=false;setBusy(false);setProgress('');}}
 async function save(){if(!draft||busy)return;setBusy(true);try{await saveDraft(draft);setDirty(false);setSaved(await listDrafts());setMessage('Perubahan draf tersimpan.');}catch{setMessage('Draf belum tersimpan. Periksa materi, pilihan soal dan jawaban.');}finally{setBusy(false);}}
 async function publish(verified:boolean){if(!draft||guard.current)return;guard.current=true;setBusy(true);try{const id=await publishDraft(draft,verified);setPublished(id);setDraft(null);setDirty(false);setFormDirty(false);setStep(3);await refresh();setSaved(await listDrafts());setMessage('Materi dan soal tersimpan di perpustakaan Anda.');}catch(error){setMessage(error instanceof Error?error.message:'Materi belum dapat diterbitkan.');}finally{guard.current=false;setBusy(false);}}
 function openDraft(next:Draft){if((dirty||formDirty)&&!window.confirm('Bahan atau draf belum disimpan. Buka draf tersimpan dan abaikan perubahan?'))return;setDraft(next);setDestination(next.subjectId?'existing':'new');setSubjectId(next.subjectId);setSubject(next.subject);setTopic(next.topic);setReference(next.data.lessons[0]?.sourceRef.title??'');setLocator(next.data.lessons[0]?.sourceRef.locator??'');setText(next.data.lessons.map(lesson=>lesson.explanation).join('\n\n'));setDirty(false);setFormDirty(false);setPublished('');setStep(2);setMessage('');}
 if(loading||error)return <LibraryState/>;
 return <><header className="page-head"><p className="eyebrow">PERLUAS RUANG BELAJAR</p><h1>Tambah materi</h1><p ref={heading} tabIndex={-1}>{step===0?'Mulai dengan memilih tempat materi Anda.':step===1?'Tambahkan bahan, lalu pilih cara membuat materi.':step===2?'Tinjau isi dan soal sebelum menyimpannya ke perpustakaan.':'Materi siap untuk dipelajari kembali.'}</p></header><FlowHeader step={step} steps={['Tujuan','Bahan','Tinjau','Selesai']} onBack={step>0&&step<3&&!busy&&!processing?back:undefined} backLabel={step===2?'Kembali ke formulir':'Ubah tujuan'}/><div role="status" aria-live="polite">{message&&<p className="notice">{message}</p>}{(busy||processing)&&<div className="notice"><p>{progress||'Menyimpan…'}</p>{busy&&progress&&<button className="plain-button text-link" onClick={()=>abort.current?.abort()}>Batalkan proses AI</button>}</div>}</div>
 {step===0&&<><div className="cards creation-choices"><button className="card choice-card" onClick={()=>{setDestination('new');setStep(1);}}><Icon name="folder"/><h2>Subjek materi baru</h2><p>Buat wadah baru untuk topik yang belum ada, lalu tambahkan materi pertamanya.</p><span className="text-link">Buat subjek <Icon name="next"/></span></button><button className="card choice-card" disabled={!subjects.length} onClick={()=>{setDestination('existing');setSubjectId(subjectId||subjects[0]?.id||'');setStep(1);}}><Icon name="layers"/><h2>Materi di subjek yang ada</h2><p>Pilih subjek dari perpustakaan, lalu tambahkan pelajaran di dalamnya.</p><span className="text-link">Pilih subjek <Icon name="next"/></span></button></div>{!subjects.length&&<p className="muted">Perpustakaan kosong. Mulai dengan subjek baru.</p>}{saved.length>0&&<section className="section"><h2>Lanjutkan draf</h2><p className="muted">Draf tersimpan terpisah dari materi yang sudah diterbitkan.</p>{saved.map(item=><button className="choice plain-button" key={item.id} onClick={()=>openDraft(item)}>{item.topic} · {item.subject}</button>)}</section>}</>}
 {step===1&&<form className="quiz-panel" onSubmit={event=>{event.preventDefault();void generate();}}><h2>{destination==='new'?'Subjek baru dan materi pertama':'Tambahkan ke subjek'}</h2><fieldset disabled={busy||processing}>{destination==='new'?<label className="field">Nama subjek baru<input required maxLength={120} value={subject} placeholder="Contoh: Fikih, Bahasa Inggris, Biologi" onChange={event=>edit(()=>setSubject(event.target.value))}/></label>:<label className="field">Subjek<select required value={subjectId} onChange={event=>edit(()=>setSubjectId(event.target.value))}>{subjects.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label>}<label className="field">Topik<input required maxLength={160} value={topic} onChange={event=>edit(()=>setTopic(event.target.value))} placeholder="Apa yang ingin dipelajari?"/></label><div className="source-choices" role="group" aria-label="Jenis bahan">{([['text','Teks / catatan','notes'],['pdf','Upload PDF','pdf'],...(!publicEdition?[['photo','Foto halaman','book']]:[])] as const).map(([kind,label,icon])=><button type="button" className="choice" aria-pressed={source===kind} key={kind} onClick={()=>setSource(kind as typeof source)}><Icon name={icon as 'notes'|'pdf'|'book'}/>{label}</button>)}</div>
 {source==='pdf'&&<section className="import-box"><h3>Tambahkan PDF materi</h3><p className="muted">Maksimal 20 MB. Pilih hingga 30 halaman per impor. PDF hasil scan memerlukan teks hasil OCR.</p><label className="field">File PDF<input type="file" accept="application/pdf,.pdf" onChange={event=>{setPdf(event.target.files?.[0]??null);setMessage('');}}/></label><div className="field-row"><label className="field">Dari halaman<input type="number" min={1} value={from} onChange={event=>setFrom(Number(event.target.value))}/></label><label className="field">Sampai halaman<input type="number" min={from} value={to} onChange={event=>setTo(Number(event.target.value))}/></label></div><button type="button" className="button secondary" disabled={!pdf} onClick={()=>void readPdf()}>Baca teks PDF</button></section>}
 {source==='photo'&&<><label className="field">Foto halaman<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={event=>{void addPhotos(event.target.files);event.target.value='';}}/></label><div className="photo-grid">{photos.map((photo,index)=><div key={`${photo.name}-${index}`}><div className="photo-preview"><Image src={photo.data} fill sizes="240px" alt={`Pratinjau halaman ${index+1}: ${photo.name}`} unoptimized/></div><button className="plain-button text-link" type="button" onClick={()=>setPhotos(current=>current.filter((_,i)=>i!==index))}>Hapus foto {index+1}</button></div>)}</div></>}
 <label className="field">{publicEdition?'Teks materi':'Teks sumber'}<textarea aria-label={publicEdition?'Teks materi':'Teks sumber'} required={source!=='photo'} rows={9} maxLength={100000} value={text} onChange={event=>edit(()=>setText(event.target.value))} placeholder="Tulis atau tempel materi. Untuk PDF, periksa hasil pembacaan di sini."/></label><p className="muted">{text.length.toLocaleString('id-ID')} karakter · {source==='pdf'?'Periksa urutan paragraf dan nomor halaman.':'Isi asli Anda tetap tersedia untuk ditinjau.'}</p><label className="field">Referensi<input required maxLength={1000} value={reference} onChange={event=>edit(()=>setReference(event.target.value))} placeholder="Buku, pemateri, catatan, atau sumber belajar"/></label><label className="field">Halaman / bab (opsional)<input maxLength={160} value={locator} onChange={event=>edit(()=>setLocator(event.target.value))}/></label><label className="field">Cara membuat materi<select value={method} onChange={event=>setMethod(event.target.value as typeof method)}><option value="manual">Manual · simpan bahan dan tambahkan soal sendiri</option><option value="browser">AI di perangkat · materi dan soal otomatis</option>{!publicEdition&&<option value="ollama">AI Ollama lokal · teks atau foto</option>}</select></label>{method==='browser'&&<><label className="field">Model AI perangkat<select value={model} onChange={event=>setModel(event.target.value)}>{deviceModels.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><p className="notice">Gratis, tanpa akun atau API berbayar. Model diunduh sekali, kemudian memproses bahan di browser Anda. Memerlukan WebGPU dan memori GPU sekitar 1,6–3,9 GB sesuai model. Unduhan dapat memakai ratusan MB hingga beberapa GB; gunakan Wi-Fi. Maksimal 6.000 karakter per proses. Hasil selalu berupa draf untuk ditinjau.</p></>}{method==='ollama'&&<p className="notice">Bahan diproses oleh Ollama pada perangkat yang menjalankan aplikasi. <Link className="text-link" href="/pengaturan">Atur kode akses AI lokal</Link>.</p>}{method==='manual'&&<p className="muted">Teks panjang dibagi menjadi pelajaran singkat tanpa menghilangkan isinya. Anda bisa menambah atau mengedit soal saat tinjauan.</p>}<button className="button" type="submit"><Icon name={method==='manual'?'next':'ai'}/>{method==='manual'?'Buat draf manual':'Buat materi & kuis dengan AI'}</button></fieldset></form>}
 {step===2&&draft&&<><div className="review-summary"><p><strong>{draft.subject}</strong> / {draft.topic}</p><p className="muted">{draft.data.lessons.length} pelajaran · {draft.data.questions.length} soal · {dirty?'Belum disimpan':'Draf tersimpan'}</p></div><fieldset disabled={busy}><DraftEditor key={draft.id} draft={draft} onChange={next=>{setDraft(next);setDirty(true);}} onSave={save} onPublish={publish} busy={busy}/></fieldset></>}
 {step===3&&<section className="quiz-panel"><Icon name="check"/><h2>Siap untuk murajaah.</h2><p>Mulai dengan satu pelajaran, lalu ulangi pemahaman Anda melalui kuis.</p><div className="actions"><Link className="button" href={`/materi/${published}`}>Baca materi yang diterbitkan</Link><Link className="text-link" href="/kuis">Buka kuis</Link><button className="plain-button text-link" onClick={()=>{setStep(0);setPublished('');setTopic('');setText('');setPdf(null);setPhotos([]);}}>Tambah materi lagi</button></div></section>}</>;
}
