import {useEffect,useState} from 'react';
type InstallPrompt=Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export function DeviceStorage(){const [ready,setReady]=useState(false);const [install,setInstall]=useState<InstallPrompt|null>(null);const [message,setMessage]=useState('');
 useEffect(()=>{let active=true;function prompt(event:Event){event.preventDefault();setInstall(event as InstallPrompt);}window.addEventListener('beforeinstallprompt',prompt);
  if('serviceWorker' in navigator)navigator.serviceWorker.register(`${process.env.NEXT_PUBLIC_BASE_PATH??'/'}sw.js`).then(()=>navigator.serviceWorker.ready).then(()=>{if(active)setReady(true);}).catch(()=>{if(active)setMessage('Salinan offline belum tersedia. Anda tetap bisa mengekspor cadangan.');});
  return()=>{active=false;window.removeEventListener('beforeinstallprompt',prompt);};},[]);
 async function persist(){try{const allowed=await navigator.storage?.persist?.();setMessage(allowed?'Penyimpanan perangkat dilindungi dari pembersihan otomatis. Tetap buat cadangan berkala.':'Data tetap tersimpan di browser. Unduh cadangan agar bisa dipindahkan atau dipulihkan.');}catch{setMessage('Gunakan Ekspor JSON di Pengaturan untuk menyimpan cadangan.');}}
 return <section className="quiz-panel backup-panel"><h2>Simpan di perangkat</h2><p>Materi, catatan, hasil kuis, dan progres tersimpan otomatis di perangkat ini. Refresh tidak menghapus data tersimpan. Gunakan cadangan JSON di Pengaturan untuk memindahkan atau memulihkan data.</p><p className="muted">{ready?'Salinan offline siap. Setelah kunjungan ini, materi dan kuis bisa dibuka tanpa internet.':'Menyiapkan salinan untuk belajar tanpa internet…'}</p><div className="actions"><button className="button" onClick={()=>void persist()}>Pertahankan penyimpanan</button>{install&&<button className="button" onClick={async()=>{await install.prompt();await install.userChoice;setInstall(null);}}>Pasang Murajaah</button>}</div><p><a className="text-link" href={`${process.env.NEXT_PUBLIC_BASE_PATH??'/'}panduan-cadangan.html`} target="_blank" rel="noopener noreferrer">Panduan cadangan dan pemulihan data di HP</a></p><p className="muted">Untuk memasang aplikasi, gunakan menu browser “Instal aplikasi” atau “Tambahkan ke Layar Utama”. Untuk memindahkan data dari localhost, ekspor JSON dari situs lama lalu impor di Pengaturan situs ini. Menghapus data browser atau aplikasi akan menghapus data belajar.</p><p role="status" aria-live="polite">{message}</p></section>;
}
