"use client";
import Link from 'next/link';
import {useParams,useRouter} from 'next/navigation';
import {useState} from 'react';
import {useLibrary,LibraryState} from '@/components/library-provider';
import {DeletionControls} from '@/components/deletion-controls';
import {ResetProgress} from '@/components/reset-progress';
import {pdfPath} from '@/lib/tuhfatul-athfal';
export default function Collection(){
 const {subjectId}=useParams<{subjectId:string}>();const router=useRouter();const {subjects,topics,lessons,readings,verifiedOnly,loading,error}=useLibrary();const [selected,setSelected]=useState<string[]>([]);
 if(loading||error)return <LibraryState/>;const subject=subjects.find(s=>s.id===subjectId);if(!subject)return <><h1>Koleksi tidak ditemukan</h1><Link className="text-link" href="/materi">Kembali ke koleksi</Link></>;
 const subjectTopics=topics.filter(t=>t.subjectId===subjectId);const entries=lessons.filter(l=>subjectTopics.some(t=>t.id===l.topicId));const selectedIds=selected.filter(id=>entries.some(l=>l.id===id));
 return <><Link className="text-link" href="/materi">Semua koleksi</Link><header className="page-head"><p className="eyebrow">MATERI BELAJAR</p><h1>{subject.title}</h1><p>{subject.description}</p><div className="actions"><Link className="text-link" href="/tambah">Tambah materi</Link><DeletionControls scope={{kind:'subject',id:subject.id}} label="Hapus seluruh koleksi" onDeleted={()=>router.replace('/materi')}/></div></header><p className="notice">Rujukan: {subject.reference}. Periksa sumber dan status setiap pelajaran.</p>{subject.id==='tuhfatul-athfal'&&<a className="text-link" href={pdfPath} target="_blank" rel="noopener noreferrer">Baca modul PDF lengkap (tab baru)</a>}{verifiedOnly&&<p className="notice">Filter materi terverifikasi aktif. Draf disembunyikan.</p>}<p>{entries.filter(l=>readings.some(r=>r.lessonId===l.id)).length} dari {entries.length} pelajaran dibaca</p><ResetProgress subjectId={subject.id} title={subject.title}/>
 {entries.length>0&&<div className="selection-tools"><label className="choice"><input type="checkbox" checked={selectedIds.length===entries.length} onChange={e=>setSelected(e.target.checked?entries.map(l=>l.id):[])}/>Pilih semua pelajaran yang ditampilkan</label><DeletionControls scope={{kind:'lessons',ids:selectedIds,subjectId}} label={`Hapus pelajaran terpilih (${selectedIds.length})`} disabled={!selectedIds.length} onDeleted={()=>setSelected([])}/></div>}
 <div className="topic-list">{subjectTopics.map((t,i)=>{const items=entries.filter(l=>l.topicId===t.id);return <section className="topic" key={t.id}><span className="index">{String(i+1).padStart(2,'0')}</span><div><h2>{t.title}</h2>{items.length?items.map(l=><div className="lesson-row" key={l.id}><label className="lesson-select"><input type="checkbox" aria-label={`Pilih ${l.title}`} checked={selectedIds.includes(l.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,l.id]:ids.filter(id=>id!==l.id))}/></label><Link className="lesson-link" href={`/materi/${encodeURIComponent(l.id)}`}>{l.title}<span className="badge">{l.status==='draft'?'Draf':'Terverifikasi'}</span>{readings.some(r=>r.lessonId===l.id)&&<small>Sudah dibaca</small>}</Link></div>):<p className="muted">{verifiedOnly?'Belum ada pelajaran terverifikasi pada topik ini.':'Materi belum tersedia.'}</p>}</div></section>;})}</div>{!subjectTopics.length&&<p className="notice">Koleksi ini belum memiliki topik.</p>}</>;
}
